/********************************************************************
* Tree2Selectordict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Tree2Selectordict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTree2Selectordict();
extern void G__cpp_setup_inheritanceTree2Selectordict();
extern void G__cpp_setup_typetableTree2Selectordict();
extern void G__cpp_setup_memvarTree2Selectordict();
extern void G__cpp_setup_globalTree2Selectordict();
extern void G__cpp_setup_memfuncTree2Selectordict();
extern void G__cpp_setup_funcTree2Selectordict();
extern void G__set_cpp_environmentTree2Selectordict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Tree2Selector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Tree2SelectordictLN_TClass;
extern G__linked_taginfo G__Tree2SelectordictLN_TBuffer;
extern G__linked_taginfo G__Tree2SelectordictLN_TMemberInspector;
extern G__linked_taginfo G__Tree2SelectordictLN_TObject;
extern G__linked_taginfo G__Tree2SelectordictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Tree2SelectordictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Tree2SelectordictLN_TList;
extern G__linked_taginfo G__Tree2SelectordictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Tree2SelectordictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Tree2SelectordictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Tree2SelectordictLN_TTree;
extern G__linked_taginfo G__Tree2SelectordictLN_TBranch;
extern G__linked_taginfo G__Tree2SelectordictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__Tree2SelectordictLN_TSelector;
extern G__linked_taginfo G__Tree2SelectordictLN_Tree2Selector;

/* STUB derived class for protected member access */
