/********************************************************************
* AdSimpleReader_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AdSimpleReader_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAdSimpleReader_Dict();
extern void G__cpp_setup_inheritanceAdSimpleReader_Dict();
extern void G__cpp_setup_typetableAdSimpleReader_Dict();
extern void G__cpp_setup_memvarAdSimpleReader_Dict();
extern void G__cpp_setup_globalAdSimpleReader_Dict();
extern void G__cpp_setup_memfuncAdSimpleReader_Dict();
extern void G__cpp_setup_funcAdSimpleReader_Dict();
extern void G__set_cpp_environmentAdSimpleReader_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AdSimpleReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AdSimpleReader_DictLN_TClass;
extern G__linked_taginfo G__AdSimpleReader_DictLN_TBuffer;
extern G__linked_taginfo G__AdSimpleReader_DictLN_TMemberInspector;
extern G__linked_taginfo G__AdSimpleReader_DictLN_TObject;
extern G__linked_taginfo G__AdSimpleReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR;
extern G__linked_taginfo G__AdSimpleReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__AdSimpleReader_DictLN_string;
extern G__linked_taginfo G__AdSimpleReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AdSimpleReader_DictLN_TList;
extern G__linked_taginfo G__AdSimpleReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AdSimpleReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__AdSimpleReader_DictLN_TTree;
extern G__linked_taginfo G__AdSimpleReader_DictLN_TBranch;
extern G__linked_taginfo G__AdSimpleReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__AdSimpleReader_DictLN_TSelector;
extern G__linked_taginfo G__AdSimpleReader_DictLN_AdSimpleReader;

/* STUB derived class for protected member access */
