FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_00.root  MC_acrylic_t_r00.root 00 
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_01.root  MC_acrylic_t_r01.root 01
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_02.root  MC_acrylic_t_r02.root 02
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_03.root  MC_acrylic_t_r03.root 03
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_04.root  MC_acrylic_t_r04.root 04
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_05.root  MC_acrylic_t_r05.root 05
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_06.root  MC_acrylic_t_r06.root 06
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_07.root  MC_acrylic_t_r07.root 07
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_08.root  MC_acrylic_t_r08.root 08
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_09.root  MC_acrylic_t_r09.root 09
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_10.root  MC_acrylic_t_r10.root 10
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_11.root  MC_acrylic_t_r11.root 11
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_12.root  MC_acrylic_t_r12.root 12
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_13.root  MC_acrylic_t_r13.root 13
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_14.root  MC_acrylic_t_r14.root 14
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_15.root  MC_acrylic_t_r15.root 15
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_16.root  MC_acrylic_t_r16.root 16
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_17.root  MC_acrylic_t_r17.root 17
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_18.root  MC_acrylic_t_r18.root 18
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_19.root  MC_acrylic_t_r19.root 19
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_20.root  MC_acrylic_t_r20.root 20
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_21.root  MC_acrylic_t_r21.root 21
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_22.root  MC_acrylic_t_r22.root 22
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_23.root  MC_acrylic_t_r23.root 23
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_24.root  MC_acrylic_t_r24.root 24
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_25.root  MC_acrylic_t_r25.root 25
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_26.root  MC_acrylic_t_r26.root 26
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_27.root  MC_acrylic_t_r27.root 27
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_28.root  MC_acrylic_t_r28.root 28
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_29.root  MC_acrylic_t_r29.root 29
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_30.root  MC_acrylic_t_r30.root 30
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_31.root  MC_acrylic_t_r31.root 31
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_32.root  MC_acrylic_t_r32.root 32
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_33.root  MC_acrylic_t_r33.root 33
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_34.root  MC_acrylic_t_r34.root 34
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_35.root  MC_acrylic_t_r35.root 35
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_36.root  MC_acrylic_t_r36.root 36
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_37.root  MC_acrylic_t_r37.root 37
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_38.root  MC_acrylic_t_r38.root 38
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_39.root  MC_acrylic_t_r39.root 39
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_40.root  MC_acrylic_t_r40.root 40
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_41.root  MC_acrylic_t_r41.root 41
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_42.root  MC_acrylic_t_r42.root 42
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_43.root  MC_acrylic_t_r43.root 43
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_44.root  MC_acrylic_t_r44.root 44
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_45.root  MC_acrylic_t_r45.root 45
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_46.root  MC_acrylic_t_r46.root 46
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_47.root  MC_acrylic_t_r47.root 47
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_48.root  MC_acrylic_t_r48.root 48
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_49.root  MC_acrylic_t_r49.root 49
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_50.root  MC_acrylic_t_r50.root 50
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_51.root  MC_acrylic_t_r51.root 51
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_52.root  MC_acrylic_t_r52.root 52
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_53.root  MC_acrylic_t_r53.root 53
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_54.root  MC_acrylic_t_r54.root 54
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_55.root  MC_acrylic_t_r55.root 55
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_56.root  MC_acrylic_t_r56.root 56
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_57.root  MC_acrylic_t_r57.root 57
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_58.root  MC_acrylic_t_r58.root 58
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_59.root  MC_acrylic_t_r59.root 59
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_60.root  MC_acrylic_t_r60.root 60
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_61.root  MC_acrylic_t_r61.root 61
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_62.root  MC_acrylic_t_r62.root 62
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_63.root  MC_acrylic_t_r63.root 63
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_64.root  MC_acrylic_t_r64.root 64
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_65.root  MC_acrylic_t_r65.root 65
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_66.root  MC_acrylic_t_r66.root 66
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_67.root  MC_acrylic_t_r67.root 67
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_68.root  MC_acrylic_t_r68.root 68
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_69.root  MC_acrylic_t_r69.root 69
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_70.root  MC_acrylic_t_r70.root 70
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_71.root  MC_acrylic_t_r71.root 71
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_72.root  MC_acrylic_t_r72.root 72
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_73.root  MC_acrylic_t_r73.root 73
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_74.root  MC_acrylic_t_r74.root 74
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_75.root  MC_acrylic_t_r75.root 75
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_76.root  MC_acrylic_t_r76.root 76
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_77.root  MC_acrylic_t_r77.root 77
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_78.root  MC_acrylic_t_r78.root 78
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_79.root  MC_acrylic_t_r79.root 79
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_80.root  MC_acrylic_t_r80.root 80
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_81.root  MC_acrylic_t_r81.root 81
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_82.root  MC_acrylic_t_r82.root 82
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_83.root  MC_acrylic_t_r83.root 83
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_84.root  MC_acrylic_t_r84.root 84
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_85.root  MC_acrylic_t_r85.root 85
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_86.root  MC_acrylic_t_r86.root 86
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_87.root  MC_acrylic_t_r87.root 87
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_88.root  MC_acrylic_t_r88.root 88
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_89.root  MC_acrylic_t_r89.root 89
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_90.root  MC_acrylic_t_r90.root 90
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_91.root  MC_acrylic_t_r91.root 91
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_92.root  MC_acrylic_t_r92.root 92
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_93.root  MC_acrylic_t_r93.root 93
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_94.root  MC_acrylic_t_r94.root 94
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_95.root  MC_acrylic_t_r95.root 95
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_96.root  MC_acrylic_t_r96.root 96
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_97.root  MC_acrylic_t_r97.root 97
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_98.root  MC_acrylic_t_r98.root 98
FastStreamer ~/depot/MC/Rec/IBD-acrylic-thick/Recon_IBD_DYB_AD1_acrylic_OavIav_1.5mm_99.root  MC_acrylic_t_r99.root 99
