//
// File generated by rootcint at Tue Mar 20 16:22:45 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME CalibReadoutHeaderReader_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "CalibReadoutHeaderReader_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CalibReadoutHeaderReader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_CalibReadoutHeaderReader(void *p = 0);
   static void *newArray_CalibReadoutHeaderReader(Long_t size, void *p);
   static void delete_CalibReadoutHeaderReader(void *p);
   static void deleteArray_CalibReadoutHeaderReader(void *p);
   static void destruct_CalibReadoutHeaderReader(void *p);
   static void streamer_CalibReadoutHeaderReader(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CalibReadoutHeaderReader*)
   {
      ::CalibReadoutHeaderReader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CalibReadoutHeaderReader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CalibReadoutHeaderReader", ::CalibReadoutHeaderReader::Class_Version(), "./CalibReadoutHeaderReader.h", 20,
                  typeid(::CalibReadoutHeaderReader), DefineBehavior(ptr, ptr),
                  &::CalibReadoutHeaderReader::Dictionary, isa_proxy, 0,
                  sizeof(::CalibReadoutHeaderReader) );
      instance.SetNew(&new_CalibReadoutHeaderReader);
      instance.SetNewArray(&newArray_CalibReadoutHeaderReader);
      instance.SetDelete(&delete_CalibReadoutHeaderReader);
      instance.SetDeleteArray(&deleteArray_CalibReadoutHeaderReader);
      instance.SetDestructor(&destruct_CalibReadoutHeaderReader);
      instance.SetStreamerFunc(&streamer_CalibReadoutHeaderReader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CalibReadoutHeaderReader*)
   {
      return GenerateInitInstanceLocal((::CalibReadoutHeaderReader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CalibReadoutHeaderReader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *CalibReadoutHeaderReader::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CalibReadoutHeaderReader::Class_Name()
{
   return "CalibReadoutHeaderReader";
}

//______________________________________________________________________________
const char *CalibReadoutHeaderReader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CalibReadoutHeaderReader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CalibReadoutHeaderReader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CalibReadoutHeaderReader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CalibReadoutHeaderReader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CalibReadoutHeaderReader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CalibReadoutHeaderReader::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CalibReadoutHeaderReader*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void CalibReadoutHeaderReader::Streamer(TBuffer &R__b)
{
   // Stream an object of class CalibReadoutHeaderReader.

   TSelector::Streamer(R__b);
}

//______________________________________________________________________________
void CalibReadoutHeaderReader::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class CalibReadoutHeaderReader.
      TClass *R__cl = ::CalibReadoutHeaderReader::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "clID", &clID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "earliest_mSec", &earliest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "earliest_mNanoSec", &earliest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "latest_mSec", &latest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "latest_mNanoSec", &latest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mSite", &context_mSite);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mSimFlag", &context_mSimFlag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mTimeStamp_mSec", &context_mTimeStamp_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mTimeStamp_mNanoSec", &context_mTimeStamp_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mDetId", &context_mDetId);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "execNumber", &execNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "jobId_m_data[4]", jobId_m_data);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "randomState", (void*)&randomState);
      R__insp.InspectMember("vector<unsigned long>", (void*)&randomState, "randomState.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputHeaders_", &inputHeaders_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputHeaders_m_entry[20]", inputHeaders_m_entry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputHeaders_m_path[20]", inputHeaders_m_path);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "site", &site);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "detector", &detector);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerNumber", &triggerNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerType", &triggerType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerTimeSec", &triggerTimeSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerTimeNanoSec", &triggerTimeNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nHitsAD", &nHitsAD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timeAD", (void*)&timeAD);
      R__insp.InspectMember("vector<float>", (void*)&timeAD, "timeAD.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chargeAD", (void*)&chargeAD);
      R__insp.InspectMember("vector<float>", (void*)&chargeAD, "chargeAD.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hitCountAD", (void*)&hitCountAD);
      R__insp.InspectMember("vector<unsigned int>", (void*)&hitCountAD, "hitCountAD.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ring", (void*)&ring);
      R__insp.InspectMember("vector<unsigned int>", (void*)&ring, "ring.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "column", (void*)&column);
      R__insp.InspectMember("vector<unsigned int>", (void*)&column, "column.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nHitsAD_calib", &nHitsAD_calib);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timeAD_calib", (void*)&timeAD_calib);
      R__insp.InspectMember("vector<float>", (void*)&timeAD_calib, "timeAD_calib.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chargeAD_calib", (void*)&chargeAD_calib);
      R__insp.InspectMember("vector<float>", (void*)&chargeAD_calib, "chargeAD_calib.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hitCountAD_calib", (void*)&hitCountAD_calib);
      R__insp.InspectMember("vector<unsigned int>", (void*)&hitCountAD_calib, "hitCountAD_calib.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "topOrBottom", (void*)&topOrBottom);
      R__insp.InspectMember("vector<unsigned int>", (void*)&topOrBottom, "topOrBottom.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acuColumn", (void*)&acuColumn);
      R__insp.InspectMember("vector<unsigned int>", (void*)&acuColumn, "acuColumn.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nHitsPool", &nHitsPool);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timePool", (void*)&timePool);
      R__insp.InspectMember("vector<float>", (void*)&timePool, "timePool.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chargePool", (void*)&chargePool);
      R__insp.InspectMember("vector<float>", (void*)&chargePool, "chargePool.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hitCountPool", (void*)&hitCountPool);
      R__insp.InspectMember("vector<unsigned int>", (void*)&hitCountPool, "hitCountPool.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wallNumber", (void*)&wallNumber);
      R__insp.InspectMember("vector<unsigned int>", (void*)&wallNumber, "wallNumber.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wallSpot", (void*)&wallSpot);
      R__insp.InspectMember("vector<unsigned int>", (void*)&wallSpot, "wallSpot.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inwardFacing", (void*)&inwardFacing);
      R__insp.InspectMember("vector<unsigned int>", (void*)&inwardFacing, "inwardFacing.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nHitsRpc", &nHitsRpc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rpcRow", (void*)&rpcRow);
      R__insp.InspectMember("vector<unsigned int>", (void*)&rpcRow, "rpcRow.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rpcColumn", (void*)&rpcColumn);
      R__insp.InspectMember("vector<unsigned int>", (void*)&rpcColumn, "rpcColumn.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rpcLayer", (void*)&rpcLayer);
      R__insp.InspectMember("vector<unsigned int>", (void*)&rpcLayer, "rpcLayer.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rpcStrip", (void*)&rpcStrip);
      R__insp.InspectMember("vector<unsigned int>", (void*)&rpcStrip, "rpcStrip.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rpcFromRot", (void*)&rpcFromRot);
      R__insp.InspectMember("vector<bool>", (void*)&rpcFromRot, "rpcFromRot.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_clID", &b_CalibReadout_CalibReadoutHeader_clID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_earliest_mSec", &b_CalibReadout_CalibReadoutHeader_earliest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_earliest_mNanoSec", &b_CalibReadout_CalibReadoutHeader_earliest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_latest_mSec", &b_CalibReadout_CalibReadoutHeader_latest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_latest_mNanoSec", &b_CalibReadout_CalibReadoutHeader_latest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_context_mSite", &b_CalibReadout_CalibReadoutHeader_context_mSite);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_context_mSimFlag", &b_CalibReadout_CalibReadoutHeader_context_mSimFlag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_context_mTimeStamp_mSec", &b_CalibReadout_CalibReadoutHeader_context_mTimeStamp_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_context_mTimeStamp_mNanoSec", &b_CalibReadout_CalibReadoutHeader_context_mTimeStamp_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_context_mDetId", &b_CalibReadout_CalibReadoutHeader_context_mDetId);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_execNumber", &b_CalibReadout_CalibReadoutHeader_execNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_jobId_m_data", &b_CalibReadout_CalibReadoutHeader_jobId_m_data);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_randomState", &b_CalibReadout_CalibReadoutHeader_randomState);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_inputHeaders_", &b_CalibReadout_CalibReadoutHeader_inputHeaders_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_inputHeaders_m_entry", &b_inputHeaders_m_entry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_inputHeaders_m_path", &b_inputHeaders_m_path);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_site", &b_CalibReadout_CalibReadoutHeader_site);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_detector", &b_CalibReadout_CalibReadoutHeader_detector);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_triggerNumber", &b_CalibReadout_CalibReadoutHeader_triggerNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_triggerType", &b_CalibReadout_CalibReadoutHeader_triggerType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_triggerTimeSec", &b_CalibReadout_CalibReadoutHeader_triggerTimeSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_triggerTimeNanoSec", &b_CalibReadout_CalibReadoutHeader_triggerTimeNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_nHitsAD", &b_CalibReadout_CalibReadoutHeader_nHitsAD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_timeAD", &b_CalibReadout_CalibReadoutHeader_timeAD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_chargeAD", &b_CalibReadout_CalibReadoutHeader_chargeAD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_hitCountAD", &b_CalibReadout_CalibReadoutHeader_hitCountAD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_ring", &b_CalibReadout_CalibReadoutHeader_ring);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_column", &b_CalibReadout_CalibReadoutHeader_column);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_nHitsAD_calib", &b_CalibReadout_CalibReadoutHeader_nHitsAD_calib);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_timeAD_calib", &b_CalibReadout_CalibReadoutHeader_timeAD_calib);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_chargeAD_calib", &b_CalibReadout_CalibReadoutHeader_chargeAD_calib);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_hitCountAD_calib", &b_CalibReadout_CalibReadoutHeader_hitCountAD_calib);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_topOrBottom", &b_CalibReadout_CalibReadoutHeader_topOrBottom);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_acuColumn", &b_CalibReadout_CalibReadoutHeader_acuColumn);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_nHitsPool", &b_CalibReadout_CalibReadoutHeader_nHitsPool);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_timePool", &b_CalibReadout_CalibReadoutHeader_timePool);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_chargePool", &b_CalibReadout_CalibReadoutHeader_chargePool);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_hitCountPool", &b_CalibReadout_CalibReadoutHeader_hitCountPool);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_wallNumber", &b_CalibReadout_CalibReadoutHeader_wallNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_wallSpot", &b_CalibReadout_CalibReadoutHeader_wallSpot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_inwardFacing", &b_CalibReadout_CalibReadoutHeader_inwardFacing);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_nHitsRpc", &b_CalibReadout_CalibReadoutHeader_nHitsRpc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_rpcRow", &b_CalibReadout_CalibReadoutHeader_rpcRow);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_rpcColumn", &b_CalibReadout_CalibReadoutHeader_rpcColumn);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_rpcLayer", &b_CalibReadout_CalibReadoutHeader_rpcLayer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_rpcStrip", &b_CalibReadout_CalibReadoutHeader_rpcStrip);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_CalibReadout_CalibReadoutHeader_rpcFromRot", &b_CalibReadout_CalibReadoutHeader_rpcFromRot);
      TSelector::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_CalibReadoutHeaderReader(void *p) {
      return  p ? new(p) ::CalibReadoutHeaderReader : new ::CalibReadoutHeaderReader;
   }
   static void *newArray_CalibReadoutHeaderReader(Long_t nElements, void *p) {
      return p ? new(p) ::CalibReadoutHeaderReader[nElements] : new ::CalibReadoutHeaderReader[nElements];
   }
   // Wrapper around operator delete
   static void delete_CalibReadoutHeaderReader(void *p) {
      delete ((::CalibReadoutHeaderReader*)p);
   }
   static void deleteArray_CalibReadoutHeaderReader(void *p) {
      delete [] ((::CalibReadoutHeaderReader*)p);
   }
   static void destruct_CalibReadoutHeaderReader(void *p) {
      typedef ::CalibReadoutHeaderReader current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_CalibReadoutHeaderReader(TBuffer &buf, void *obj) {
      ((::CalibReadoutHeaderReader*)obj)->::CalibReadoutHeaderReader::Streamer(buf);
   }
} // end of namespace ROOT for class ::CalibReadoutHeaderReader

/********************************************************
* CalibReadoutHeaderReader_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableCalibReadoutHeaderReader_Dict();

extern "C" void G__set_cpp_environmentCalibReadoutHeaderReader_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("CalibReadoutHeaderReader.h");
  G__cpp_reset_tagtableCalibReadoutHeaderReader_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevCalibReadoutHeaderReader_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CalibReadoutHeaderReader */
static int G__CalibReadoutHeaderReader_Dict_534_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CalibReadoutHeaderReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CalibReadoutHeaderReader((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) CalibReadoutHeaderReader((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new CalibReadoutHeaderReader[n];
       } else {
         p = new((void*) gvp) CalibReadoutHeaderReader[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new CalibReadoutHeaderReader;
       } else {
         p = new((void*) gvp) CalibReadoutHeaderReader;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibReadoutHeaderReader_Dict_534_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CalibReadoutHeaderReader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibReadoutHeaderReader_Dict_534_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CalibReadoutHeaderReader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibReadoutHeaderReader_Dict_534_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CalibReadoutHeaderReader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibReadoutHeaderReader_Dict_534_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CalibReadoutHeaderReader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibReadoutHeaderReader_Dict_534_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CalibReadoutHeaderReader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibReadoutHeaderReader_Dict_534_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CalibReadoutHeaderReader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibReadoutHeaderReader_Dict_534_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CalibReadoutHeaderReader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibReadoutHeaderReader_Dict_534_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CalibReadoutHeaderReader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibReadoutHeaderReader_Dict_534_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CalibReadoutHeaderReader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CalibReadoutHeaderReader G__TCalibReadoutHeaderReader;
static int G__CalibReadoutHeaderReader_Dict_534_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CalibReadoutHeaderReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CalibReadoutHeaderReader*) (soff+(sizeof(CalibReadoutHeaderReader)*i)))->~G__TCalibReadoutHeaderReader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CalibReadoutHeaderReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CalibReadoutHeaderReader*) (soff))->~G__TCalibReadoutHeaderReader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CalibReadoutHeaderReader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncCalibReadoutHeaderReader_Dict {
 public:
  G__Sizep2memfuncCalibReadoutHeaderReader_Dict(): p(&G__Sizep2memfuncCalibReadoutHeaderReader_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncCalibReadoutHeaderReader_Dict::*p)();
};

size_t G__get_sizep2memfuncCalibReadoutHeaderReader_Dict()
{
  G__Sizep2memfuncCalibReadoutHeaderReader_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceCalibReadoutHeaderReader_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader))) {
     CalibReadoutHeaderReader *G__Lderived;
     G__Lderived=(CalibReadoutHeaderReader*)0x1000;
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader),G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader),G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableCalibReadoutHeaderReader_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CalibReadoutHeaderReader */
static void G__setup_memvarCalibReadoutHeaderReader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader));
   { CalibReadoutHeaderReader *p; p=(CalibReadoutHeaderReader*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->clID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"clID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->earliest_mSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"earliest_mSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->earliest_mNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"earliest_mNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->latest_mSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"latest_mSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->latest_mNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"latest_mNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mSite)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mSite=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mSimFlag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mSimFlag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mTimeStamp_mSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mTimeStamp_mSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mTimeStamp_mNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mTimeStamp_mNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mDetId)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mDetId=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->execNumber)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"execNumber=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jobId_m_data)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"jobId_m_data[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->randomState)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR),G__defined_typename("vector<unsigned long>"),-1,1,"randomState=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->inputHeaders_)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"inputHeaders_=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->inputHeaders_m_entry)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"inputHeaders_m_entry[20]=",0,"[inputHeaders_]");
   G__memvar_setup((void*)((long)(&p->inputHeaders_m_path)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_string),-1,-1,1,"inputHeaders_m_path[20]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->site)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"site=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->detector)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"detector=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerNumber)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"triggerNumber=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerType)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"triggerType=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerTimeSec)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"triggerTimeSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerTimeNanoSec)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"triggerTimeNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nHitsAD)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"nHitsAD=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->timeAD)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,1,"timeAD=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chargeAD)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,1,"chargeAD=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hitCountAD)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"hitCountAD=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ring)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"ring=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->column)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"column=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nHitsAD_calib)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"nHitsAD_calib=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->timeAD_calib)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,1,"timeAD_calib=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chargeAD_calib)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,1,"chargeAD_calib=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hitCountAD_calib)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"hitCountAD_calib=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->topOrBottom)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"topOrBottom=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->acuColumn)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"acuColumn=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nHitsPool)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"nHitsPool=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->timePool)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,1,"timePool=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->chargePool)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,1,"chargePool=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hitCountPool)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"hitCountPool=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->wallNumber)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"wallNumber=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->wallSpot)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"wallSpot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->inwardFacing)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"inwardFacing=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nHitsRpc)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"nHitsRpc=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rpcRow)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"rpcRow=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rpcColumn)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"rpcColumn=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rpcLayer)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"rpcLayer=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rpcStrip)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),G__defined_typename("vector<unsigned int>"),-1,1,"rpcStrip=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rpcFromRot)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<bool>"),-1,1,"rpcFromRot=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_clID)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_clID=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_earliest_mSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_earliest_mSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_earliest_mNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_earliest_mNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_latest_mSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_latest_mSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_latest_mNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_latest_mNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_context_mSite)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_context_mSite=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_context_mSimFlag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_context_mSimFlag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_context_mTimeStamp_mSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_context_mTimeStamp_mSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_context_mTimeStamp_mNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_context_mTimeStamp_mNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_context_mDetId)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_context_mDetId=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_execNumber)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_execNumber=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_jobId_m_data)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_jobId_m_data=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_randomState)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_randomState=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_inputHeaders_)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_inputHeaders_=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_inputHeaders_m_entry)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_inputHeaders_m_entry=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_inputHeaders_m_path)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_inputHeaders_m_path=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_site)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_site=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_detector)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_detector=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_triggerNumber)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_triggerNumber=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_triggerType)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_triggerType=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_triggerTimeSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_triggerTimeSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_triggerTimeNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_triggerTimeNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_nHitsAD)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_nHitsAD=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_timeAD)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_timeAD=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_chargeAD)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_chargeAD=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_hitCountAD)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_hitCountAD=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_ring)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_ring=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_column)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_column=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_nHitsAD_calib)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_nHitsAD_calib=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_timeAD_calib)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_timeAD_calib=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_chargeAD_calib)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_chargeAD_calib=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_hitCountAD_calib)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_hitCountAD_calib=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_topOrBottom)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_topOrBottom=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_acuColumn)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_acuColumn=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_nHitsPool)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_nHitsPool=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_timePool)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_timePool=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_chargePool)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_chargePool=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_hitCountPool)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_hitCountPool=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_wallNumber)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_wallNumber=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_wallSpot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_wallSpot=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_inwardFacing)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_inwardFacing=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_nHitsRpc)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_nHitsRpc=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_rpcRow)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_rpcRow=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_rpcColumn)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_rpcColumn=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_rpcLayer)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_rpcLayer=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_rpcStrip)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_rpcStrip=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_CalibReadout_CalibReadoutHeader_rpcFromRot)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TBranch),-1,-1,1,"b_CalibReadout_CalibReadoutHeader_rpcFromRot=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarCalibReadoutHeaderReader_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCalibReadoutHeaderReader(void) {
   /* CalibReadoutHeaderReader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader));
   G__memfunc_setup("CalibReadoutHeaderReader",2379,G__CalibReadoutHeaderReader_Dict_534_0_1, 105, G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Version",742,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Begin",485,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveBegin",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetOption",933,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetObject",899,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputList",1240,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputList",1357,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveTerminate",1444,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__CalibReadoutHeaderReader_Dict_534_0_15, 85, G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&CalibReadoutHeaderReader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__CalibReadoutHeaderReader_Dict_534_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CalibReadoutHeaderReader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__CalibReadoutHeaderReader_Dict_534_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&CalibReadoutHeaderReader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__CalibReadoutHeaderReader_Dict_534_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&CalibReadoutHeaderReader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__CalibReadoutHeaderReader_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__CalibReadoutHeaderReader_Dict_534_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__CalibReadoutHeaderReader_Dict_534_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CalibReadoutHeaderReader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__CalibReadoutHeaderReader_Dict_534_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CalibReadoutHeaderReader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__CalibReadoutHeaderReader_Dict_534_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CalibReadoutHeaderReader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__CalibReadoutHeaderReader_Dict_534_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CalibReadoutHeaderReader::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~CalibReadoutHeaderReader", 2505, G__CalibReadoutHeaderReader_Dict_534_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncCalibReadoutHeaderReader_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalCalibReadoutHeaderReader_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcCalibReadoutHeaderReader_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR = { "vector<unsigned long,allocator<unsigned long> >" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEboolcOallocatorlEboolgRsPgR = { "vector<bool,allocator<bool> >" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader = { "CalibReadoutHeaderReader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableCalibReadoutHeaderReader_Dict() {
  G__CalibReadoutHeaderReader_DictLN_TClass.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_TBuffer.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_TMemberInspector.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_TObject.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_vectorlEboolcOallocatorlEboolgRsPgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_string.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_TList.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_TTree.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_TBranch.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_TSelector.tagnum = -1 ;
  G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableCalibReadoutHeaderReader_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_vectorlEboolcOallocatorlEboolgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_string);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_TList);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_TTree);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_TSelector);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader),sizeof(CalibReadoutHeaderReader),-1,29952,(char*)NULL,G__setup_memvarCalibReadoutHeaderReader,G__setup_memfuncCalibReadoutHeaderReader);
}
extern "C" void G__cpp_setupCalibReadoutHeaderReader_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupCalibReadoutHeaderReader_Dict()");
  G__set_cpp_environmentCalibReadoutHeaderReader_Dict();
  G__cpp_setup_tagtableCalibReadoutHeaderReader_Dict();

  G__cpp_setup_inheritanceCalibReadoutHeaderReader_Dict();

  G__cpp_setup_typetableCalibReadoutHeaderReader_Dict();

  G__cpp_setup_memvarCalibReadoutHeaderReader_Dict();

  G__cpp_setup_memfuncCalibReadoutHeaderReader_Dict();
  G__cpp_setup_globalCalibReadoutHeaderReader_Dict();
  G__cpp_setup_funcCalibReadoutHeaderReader_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncCalibReadoutHeaderReader_Dict();
  return;
}
class G__cpp_setup_initCalibReadoutHeaderReader_Dict {
  public:
    G__cpp_setup_initCalibReadoutHeaderReader_Dict() { G__add_setup_func("CalibReadoutHeaderReader_Dict",(G__incsetup)(&G__cpp_setupCalibReadoutHeaderReader_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initCalibReadoutHeaderReader_Dict() { G__remove_setup_func("CalibReadoutHeaderReader_Dict"); }
};
G__cpp_setup_initCalibReadoutHeaderReader_Dict G__cpp_setup_initializerCalibReadoutHeaderReader_Dict;

