//
// File generated by rootcint at Tue Mar 20 15:37:19 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME AdSimpleReader_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "AdSimpleReader_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void AdSimpleReader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_AdSimpleReader(void *p = 0);
   static void *newArray_AdSimpleReader(Long_t size, void *p);
   static void delete_AdSimpleReader(void *p);
   static void deleteArray_AdSimpleReader(void *p);
   static void destruct_AdSimpleReader(void *p);
   static void streamer_AdSimpleReader(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::AdSimpleReader*)
   {
      ::AdSimpleReader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::AdSimpleReader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("AdSimpleReader", ::AdSimpleReader::Class_Version(), "./AdSimpleReader.h", 17,
                  typeid(::AdSimpleReader), DefineBehavior(ptr, ptr),
                  &::AdSimpleReader::Dictionary, isa_proxy, 0,
                  sizeof(::AdSimpleReader) );
      instance.SetNew(&new_AdSimpleReader);
      instance.SetNewArray(&newArray_AdSimpleReader);
      instance.SetDelete(&delete_AdSimpleReader);
      instance.SetDeleteArray(&deleteArray_AdSimpleReader);
      instance.SetDestructor(&destruct_AdSimpleReader);
      instance.SetStreamerFunc(&streamer_AdSimpleReader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::AdSimpleReader*)
   {
      return GenerateInitInstanceLocal((::AdSimpleReader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::AdSimpleReader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *AdSimpleReader::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *AdSimpleReader::Class_Name()
{
   return "AdSimpleReader";
}

//______________________________________________________________________________
const char *AdSimpleReader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::AdSimpleReader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int AdSimpleReader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::AdSimpleReader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void AdSimpleReader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::AdSimpleReader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *AdSimpleReader::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::AdSimpleReader*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void AdSimpleReader::Streamer(TBuffer &R__b)
{
   // Stream an object of class AdSimpleReader.

   TSelector::Streamer(R__b);
}

//______________________________________________________________________________
void AdSimpleReader::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class AdSimpleReader.
      TClass *R__cl = ::AdSimpleReader::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "clID", &clID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "earliest_mSec", &earliest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "earliest_mNanoSec", &earliest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "latest_mSec", &latest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "latest_mNanoSec", &latest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mSite", &context_mSite);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mSimFlag", &context_mSimFlag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mTimeStamp_mSec", &context_mTimeStamp_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mTimeStamp_mNanoSec", &context_mTimeStamp_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mDetId", &context_mDetId);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "execNumber", &execNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "jobId_m_data[4]", jobId_m_data);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "randomState", (void*)&randomState);
      R__insp.InspectMember("vector<unsigned long>", (void*)&randomState, "randomState.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputHeaders_", &inputHeaders_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputHeaders_m_entry[2]", inputHeaders_m_entry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputHeaders_m_path[2]", inputHeaders_m_path);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "site", &site);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "detector", &detector);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerType", &triggerType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerNumber", &triggerNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerTimeSec", &triggerTimeSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerTimeNanoSec", &triggerTimeNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energy", &energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rawEvis", &rawEvis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "enrec", &enrec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "eprec", &eprec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x", &x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y", &y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "z", &z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t", &t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dx", &dx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dy", &dy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dz", &dz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dt", &dt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energyStatus", &energyStatus);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "positionStatus", &positionStatus);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "directionStatus", &directionStatus);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energyQuality", &energyQuality);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "positionQuality", &positionQuality);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "directionQuality", &directionQuality);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "errorMatrixDim", &errorMatrixDim);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "errorMatrix", (void*)&errorMatrix);
      R__insp.InspectMember("vector<float>", (void*)&errorMatrix, "errorMatrix.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_clID", &b_Rec_AdSimple_clID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_earliest_mSec", &b_Rec_AdSimple_earliest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_earliest_mNanoSec", &b_Rec_AdSimple_earliest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_latest_mSec", &b_Rec_AdSimple_latest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_latest_mNanoSec", &b_Rec_AdSimple_latest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_context_mSite", &b_Rec_AdSimple_context_mSite);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_context_mSimFlag", &b_Rec_AdSimple_context_mSimFlag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_context_mTimeStamp_mSec", &b_Rec_AdSimple_context_mTimeStamp_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_context_mTimeStamp_mNanoSec", &b_Rec_AdSimple_context_mTimeStamp_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_context_mDetId", &b_Rec_AdSimple_context_mDetId);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_execNumber", &b_Rec_AdSimple_execNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_jobId_m_data", &b_Rec_AdSimple_jobId_m_data);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_randomState", &b_Rec_AdSimple_randomState);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_inputHeaders_", &b_Rec_AdSimple_inputHeaders_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_inputHeaders_m_entry", &b_inputHeaders_m_entry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_inputHeaders_m_path", &b_inputHeaders_m_path);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_site", &b_Rec_AdSimple_site);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_detector", &b_Rec_AdSimple_detector);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_triggerType", &b_Rec_AdSimple_triggerType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_triggerNumber", &b_Rec_AdSimple_triggerNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_triggerTimeSec", &b_Rec_AdSimple_triggerTimeSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_triggerTimeNanoSec", &b_Rec_AdSimple_triggerTimeNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_energy", &b_Rec_AdSimple_energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_rawEvis", &b_Rec_AdSimple_rawEvis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_enrec", &b_Rec_AdSimple_enrec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_eprec", &b_Rec_AdSimple_eprec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_x", &b_Rec_AdSimple_x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_y", &b_Rec_AdSimple_y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_z", &b_Rec_AdSimple_z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_t", &b_Rec_AdSimple_t);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_dx", &b_Rec_AdSimple_dx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_dy", &b_Rec_AdSimple_dy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_dz", &b_Rec_AdSimple_dz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_dt", &b_Rec_AdSimple_dt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_energyStatus", &b_Rec_AdSimple_energyStatus);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_positionStatus", &b_Rec_AdSimple_positionStatus);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_directionStatus", &b_Rec_AdSimple_directionStatus);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_energyQuality", &b_Rec_AdSimple_energyQuality);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_positionQuality", &b_Rec_AdSimple_positionQuality);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_directionQuality", &b_Rec_AdSimple_directionQuality);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_errorMatrixDim", &b_Rec_AdSimple_errorMatrixDim);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Rec_AdSimple_errorMatrix", &b_Rec_AdSimple_errorMatrix);
      TSelector::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_AdSimpleReader(void *p) {
      return  p ? new(p) ::AdSimpleReader : new ::AdSimpleReader;
   }
   static void *newArray_AdSimpleReader(Long_t nElements, void *p) {
      return p ? new(p) ::AdSimpleReader[nElements] : new ::AdSimpleReader[nElements];
   }
   // Wrapper around operator delete
   static void delete_AdSimpleReader(void *p) {
      delete ((::AdSimpleReader*)p);
   }
   static void deleteArray_AdSimpleReader(void *p) {
      delete [] ((::AdSimpleReader*)p);
   }
   static void destruct_AdSimpleReader(void *p) {
      typedef ::AdSimpleReader current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_AdSimpleReader(TBuffer &buf, void *obj) {
      ((::AdSimpleReader*)obj)->::AdSimpleReader::Streamer(buf);
   }
} // end of namespace ROOT for class ::AdSimpleReader

/********************************************************
* AdSimpleReader_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableAdSimpleReader_Dict();

extern "C" void G__set_cpp_environmentAdSimpleReader_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("AdSimpleReader.h");
  G__cpp_reset_tagtableAdSimpleReader_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevAdSimpleReader_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* AdSimpleReader */
static int G__AdSimpleReader_Dict_534_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   AdSimpleReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new AdSimpleReader((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) AdSimpleReader((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new AdSimpleReader[n];
       } else {
         p = new((void*) gvp) AdSimpleReader[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new AdSimpleReader;
       } else {
         p = new((void*) gvp) AdSimpleReader;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_AdSimpleReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AdSimpleReader_Dict_534_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) AdSimpleReader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AdSimpleReader_Dict_534_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) AdSimpleReader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AdSimpleReader_Dict_534_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) AdSimpleReader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AdSimpleReader_Dict_534_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      AdSimpleReader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AdSimpleReader_Dict_534_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((AdSimpleReader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AdSimpleReader_Dict_534_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) AdSimpleReader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AdSimpleReader_Dict_534_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) AdSimpleReader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AdSimpleReader_Dict_534_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) AdSimpleReader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AdSimpleReader_Dict_534_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) AdSimpleReader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef AdSimpleReader G__TAdSimpleReader;
static int G__AdSimpleReader_Dict_534_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (AdSimpleReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((AdSimpleReader*) (soff+(sizeof(AdSimpleReader)*i)))->~G__TAdSimpleReader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (AdSimpleReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((AdSimpleReader*) (soff))->~G__TAdSimpleReader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* AdSimpleReader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncAdSimpleReader_Dict {
 public:
  G__Sizep2memfuncAdSimpleReader_Dict(): p(&G__Sizep2memfuncAdSimpleReader_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncAdSimpleReader_Dict::*p)();
};

size_t G__get_sizep2memfuncAdSimpleReader_Dict()
{
  G__Sizep2memfuncAdSimpleReader_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceAdSimpleReader_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__AdSimpleReader_DictLN_AdSimpleReader))) {
     AdSimpleReader *G__Lderived;
     G__Lderived=(AdSimpleReader*)0x1000;
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__AdSimpleReader_DictLN_AdSimpleReader),G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__AdSimpleReader_DictLN_AdSimpleReader),G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableAdSimpleReader_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* AdSimpleReader */
static void G__setup_memvarAdSimpleReader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__AdSimpleReader_DictLN_AdSimpleReader));
   { AdSimpleReader *p; p=(AdSimpleReader*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->clID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"clID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->earliest_mSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"earliest_mSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->earliest_mNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"earliest_mNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->latest_mSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"latest_mSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->latest_mNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"latest_mNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mSite)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mSite=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mSimFlag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mSimFlag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mTimeStamp_mSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mTimeStamp_mSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mTimeStamp_mNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mTimeStamp_mNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mDetId)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mDetId=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->execNumber)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"execNumber=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jobId_m_data)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"jobId_m_data[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->randomState)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR),G__defined_typename("vector<unsigned long>"),-1,1,"randomState=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->inputHeaders_)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"inputHeaders_=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->inputHeaders_m_entry)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"inputHeaders_m_entry[2]=",0,"[inputHeaders_]");
   G__memvar_setup((void*)((long)(&p->inputHeaders_m_path)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_string),-1,-1,1,"inputHeaders_m_path[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->site)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"site=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->detector)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"detector=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerType)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"triggerType=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerNumber)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"triggerNumber=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerTimeSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"triggerTimeSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerTimeNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"triggerTimeNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->energy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"energy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rawEvis)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"rawEvis=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->enrec)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"enrec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->eprec)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"eprec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"t=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dx)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dt)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->energyStatus)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"energyStatus=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->positionStatus)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"positionStatus=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->directionStatus)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"directionStatus=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->energyQuality)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"energyQuality=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->positionQuality)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"positionQuality=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->directionQuality)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"directionQuality=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->errorMatrixDim)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"errorMatrixDim=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->errorMatrix)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,1,"errorMatrix=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_clID)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_clID=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_earliest_mSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_earliest_mSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_earliest_mNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_earliest_mNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_latest_mSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_latest_mSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_latest_mNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_latest_mNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_context_mSite)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_context_mSite=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_context_mSimFlag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_context_mSimFlag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_context_mTimeStamp_mSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_context_mTimeStamp_mSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_context_mTimeStamp_mNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_context_mTimeStamp_mNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_context_mDetId)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_context_mDetId=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_execNumber)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_execNumber=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_jobId_m_data)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_jobId_m_data=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_randomState)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_randomState=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_inputHeaders_)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_inputHeaders_=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_inputHeaders_m_entry)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_inputHeaders_m_entry=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_inputHeaders_m_path)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_inputHeaders_m_path=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_site)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_site=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_detector)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_detector=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_triggerType)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_triggerType=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_triggerNumber)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_triggerNumber=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_triggerTimeSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_triggerTimeSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_triggerTimeNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_triggerTimeNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_energy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_energy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_rawEvis)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_rawEvis=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_enrec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_enrec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_eprec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_eprec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_x)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_x=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_t)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_t=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_dx)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_dx=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_dy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_dy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_dz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_dz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_dt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_dt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_energyStatus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_energyStatus=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_positionStatus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_positionStatus=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_directionStatus)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_directionStatus=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_energyQuality)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_energyQuality=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_positionQuality)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_positionQuality=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_directionQuality)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_directionQuality=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_errorMatrixDim)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_errorMatrixDim=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Rec_AdSimple_errorMatrix)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TBranch),-1,-1,1,"b_Rec_AdSimple_errorMatrix=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarAdSimpleReader_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncAdSimpleReader(void) {
   /* AdSimpleReader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__AdSimpleReader_DictLN_AdSimpleReader));
   G__memfunc_setup("AdSimpleReader",1378,G__AdSimpleReader_Dict_534_0_1, 105, G__get_linked_tagnum(&G__AdSimpleReader_DictLN_AdSimpleReader), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Version",742,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Begin",485,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveBegin",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetOption",933,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetObject",899,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputList",1240,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputList",1357,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveTerminate",1444,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__AdSimpleReader_Dict_534_0_15, 85, G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&AdSimpleReader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__AdSimpleReader_Dict_534_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&AdSimpleReader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__AdSimpleReader_Dict_534_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&AdSimpleReader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__AdSimpleReader_Dict_534_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&AdSimpleReader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__AdSimpleReader_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__AdSimpleReader_Dict_534_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__AdSimpleReader_Dict_534_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&AdSimpleReader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__AdSimpleReader_Dict_534_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&AdSimpleReader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__AdSimpleReader_Dict_534_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&AdSimpleReader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__AdSimpleReader_Dict_534_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&AdSimpleReader::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~AdSimpleReader", 1504, G__AdSimpleReader_Dict_534_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncAdSimpleReader_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalAdSimpleReader_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcAdSimpleReader_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__AdSimpleReader_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR = { "vector<unsigned long,allocator<unsigned long> >" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__AdSimpleReader_DictLN_AdSimpleReader = { "AdSimpleReader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableAdSimpleReader_Dict() {
  G__AdSimpleReader_DictLN_TClass.tagnum = -1 ;
  G__AdSimpleReader_DictLN_TBuffer.tagnum = -1 ;
  G__AdSimpleReader_DictLN_TMemberInspector.tagnum = -1 ;
  G__AdSimpleReader_DictLN_TObject.tagnum = -1 ;
  G__AdSimpleReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR.tagnum = -1 ;
  G__AdSimpleReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__AdSimpleReader_DictLN_string.tagnum = -1 ;
  G__AdSimpleReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AdSimpleReader_DictLN_TList.tagnum = -1 ;
  G__AdSimpleReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AdSimpleReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__AdSimpleReader_DictLN_TTree.tagnum = -1 ;
  G__AdSimpleReader_DictLN_TBranch.tagnum = -1 ;
  G__AdSimpleReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__AdSimpleReader_DictLN_TSelector.tagnum = -1 ;
  G__AdSimpleReader_DictLN_AdSimpleReader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableAdSimpleReader_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_string);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_TList);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_TTree);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_TSelector);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__AdSimpleReader_DictLN_AdSimpleReader),sizeof(AdSimpleReader),-1,29952,(char*)NULL,G__setup_memvarAdSimpleReader,G__setup_memfuncAdSimpleReader);
}
extern "C" void G__cpp_setupAdSimpleReader_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupAdSimpleReader_Dict()");
  G__set_cpp_environmentAdSimpleReader_Dict();
  G__cpp_setup_tagtableAdSimpleReader_Dict();

  G__cpp_setup_inheritanceAdSimpleReader_Dict();

  G__cpp_setup_typetableAdSimpleReader_Dict();

  G__cpp_setup_memvarAdSimpleReader_Dict();

  G__cpp_setup_memfuncAdSimpleReader_Dict();
  G__cpp_setup_globalAdSimpleReader_Dict();
  G__cpp_setup_funcAdSimpleReader_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncAdSimpleReader_Dict();
  return;
}
class G__cpp_setup_initAdSimpleReader_Dict {
  public:
    G__cpp_setup_initAdSimpleReader_Dict() { G__add_setup_func("AdSimpleReader_Dict",(G__incsetup)(&G__cpp_setupAdSimpleReader_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initAdSimpleReader_Dict() { G__remove_setup_func("AdSimpleReader_Dict"); }
};
G__cpp_setup_initAdSimpleReader_Dict G__cpp_setup_initializerAdSimpleReader_Dict;

