/********************************************************************
* EventReaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EventReaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEventReaderDict();
extern void G__cpp_setup_inheritanceEventReaderDict();
extern void G__cpp_setup_typetableEventReaderDict();
extern void G__cpp_setup_memvarEventReaderDict();
extern void G__cpp_setup_globalEventReaderDict();
extern void G__cpp_setup_memfuncEventReaderDict();
extern void G__cpp_setup_funcEventReaderDict();
extern void G__set_cpp_environmentEventReaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EventReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventReaderDictLN_TClass;
extern G__linked_taginfo G__EventReaderDictLN_TBuffer;
extern G__linked_taginfo G__EventReaderDictLN_TMemberInspector;
extern G__linked_taginfo G__EventReaderDictLN_TObject;
extern G__linked_taginfo G__EventReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EventReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventReaderDictLN_TList;
extern G__linked_taginfo G__EventReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EventReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EventReaderDictLN_TTree;
extern G__linked_taginfo G__EventReaderDictLN_TBranch;
extern G__linked_taginfo G__EventReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EventReaderDictLN_TSelector;
extern G__linked_taginfo G__EventReaderDictLN_EventReader;

/* STUB derived class for protected member access */
