/********************************************************************
* StreamReaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error StreamReaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableStreamReaderDict();
extern void G__cpp_setup_inheritanceStreamReaderDict();
extern void G__cpp_setup_typetableStreamReaderDict();
extern void G__cpp_setup_memvarStreamReaderDict();
extern void G__cpp_setup_globalStreamReaderDict();
extern void G__cpp_setup_memfuncStreamReaderDict();
extern void G__cpp_setup_funcStreamReaderDict();
extern void G__set_cpp_environmentStreamReaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "StreamReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__StreamReaderDictLN_TClass;
extern G__linked_taginfo G__StreamReaderDictLN_TBuffer;
extern G__linked_taginfo G__StreamReaderDictLN_TMemberInspector;
extern G__linked_taginfo G__StreamReaderDictLN_TObject;
extern G__linked_taginfo G__StreamReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__StreamReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StreamReaderDictLN_TList;
extern G__linked_taginfo G__StreamReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__StreamReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StreamReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__StreamReaderDictLN_TTree;
extern G__linked_taginfo G__StreamReaderDictLN_TBranch;
extern G__linked_taginfo G__StreamReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__StreamReaderDictLN_TSelector;
extern G__linked_taginfo G__StreamReaderDictLN_StreamReader;

/* STUB derived class for protected member access */
