//
// File generated by rootcint at Sat Jul 14 23:37:17 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TreeReaderDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TreeReaderDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TreeReader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TreeReader(void *p = 0);
   static void *newArray_TreeReader(Long_t size, void *p);
   static void delete_TreeReader(void *p);
   static void deleteArray_TreeReader(void *p);
   static void destruct_TreeReader(void *p);
   static void streamer_TreeReader(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TreeReader*)
   {
      ::TreeReader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TreeReader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TreeReader", ::TreeReader::Class_Version(), "./TreeReader.h", 15,
                  typeid(::TreeReader), DefineBehavior(ptr, ptr),
                  &::TreeReader::Dictionary, isa_proxy, 0,
                  sizeof(::TreeReader) );
      instance.SetNew(&new_TreeReader);
      instance.SetNewArray(&newArray_TreeReader);
      instance.SetDelete(&delete_TreeReader);
      instance.SetDeleteArray(&deleteArray_TreeReader);
      instance.SetDestructor(&destruct_TreeReader);
      instance.SetStreamerFunc(&streamer_TreeReader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TreeReader*)
   {
      return GenerateInitInstanceLocal((::TreeReader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TreeReader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TreeReader::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TreeReader::Class_Name()
{
   return "TreeReader";
}

//______________________________________________________________________________
const char *TreeReader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TreeReader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TreeReader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TreeReader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TreeReader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TreeReader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TreeReader::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TreeReader*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TreeReader::Streamer(TBuffer &R__b)
{
   // Stream an object of class TreeReader.

   TSelector::Streamer(R__b);
}

//______________________________________________________________________________
void TreeReader::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TreeReader.
      TClass *R__cl = ::TreeReader::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Run", &Run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Det", &Det);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T2PrevMu", &T2PrevMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T2PrevPlMu", &T2PrevPlMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T2PrevAdMu", &T2PrevAdMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T2PrevShMu", &T2PrevShMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T2PrevNetMu", &T2PrevNetMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Fold", &Fold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigSec[2]", TrigSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigNano[2]", TrigNano);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E[2]", E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "X[2]", X);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Y[2]", Y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Z[2]", Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "D2First[2]", D2First);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T2PrevSubEvt[2]", T2PrevSubEvt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigSecT[2]", TrigSecT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigNanoT[2]", TrigNanoT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ET[2]", ET);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "XT[2]", XT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "YT[2]", YT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ZT[2]", ZT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "D2FirstT[2]", D2FirstT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T2PrevSubEvtT[2]", T2PrevSubEvtT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "XCpt[2]", XCpt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "YCpt[2]", YCpt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ZCpt[2]", ZCpt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Run", &b_Run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Det", &b_Det);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_T2PrevMu", &b_T2PrevMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_T2PrevPlMu", &b_T2PrevPlMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_T2PrevAdMu", &b_T2PrevAdMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_T2PrevShMu", &b_T2PrevShMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_T2PrevNetMu", &b_T2PrevNetMu);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Fold", &b_Fold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigSec", &b_TrigSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigNano", &b_TrigNano);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_E", &b_E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_X", &b_X);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Y", &b_Y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Z", &b_Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_D2First", &b_D2First);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_T2PrevSubEvt", &b_T2PrevSubEvt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigSecT", &b_TrigSecT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigNanoT", &b_TrigNanoT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ET", &b_ET);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_XT", &b_XT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_YT", &b_YT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ZT", &b_ZT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_D2FirstT", &b_D2FirstT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_T2PrevSubEvtT", &b_T2PrevSubEvtT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_XCpt", &b_XCpt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_YCpt", &b_YCpt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ZCpt", &b_ZCpt);
      TSelector::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TreeReader(void *p) {
      return  p ? new(p) ::TreeReader : new ::TreeReader;
   }
   static void *newArray_TreeReader(Long_t nElements, void *p) {
      return p ? new(p) ::TreeReader[nElements] : new ::TreeReader[nElements];
   }
   // Wrapper around operator delete
   static void delete_TreeReader(void *p) {
      delete ((::TreeReader*)p);
   }
   static void deleteArray_TreeReader(void *p) {
      delete [] ((::TreeReader*)p);
   }
   static void destruct_TreeReader(void *p) {
      typedef ::TreeReader current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TreeReader(TBuffer &buf, void *obj) {
      ((::TreeReader*)obj)->::TreeReader::Streamer(buf);
   }
} // end of namespace ROOT for class ::TreeReader

/********************************************************
* TreeReaderDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTreeReaderDict();

extern "C" void G__set_cpp_environmentTreeReaderDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TreeReader.h");
  G__cpp_reset_tagtableTreeReaderDict();
}
#include <new>
extern "C" int G__cpp_dllrevTreeReaderDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TreeReader */
static int G__TreeReaderDict_534_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TreeReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TreeReader((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) TreeReader((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new TreeReader[n];
       } else {
         p = new((void*) gvp) TreeReader[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new TreeReader;
       } else {
         p = new((void*) gvp) TreeReader;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TreeReaderDictLN_TreeReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeReaderDict_534_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TreeReader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeReaderDict_534_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TreeReader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeReaderDict_534_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TreeReader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeReaderDict_534_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TreeReader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeReaderDict_534_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TreeReader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeReaderDict_534_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TreeReader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeReaderDict_534_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TreeReader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeReaderDict_534_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TreeReader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TreeReaderDict_534_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TreeReader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TreeReader G__TTreeReader;
static int G__TreeReaderDict_534_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TreeReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TreeReader*) (soff+(sizeof(TreeReader)*i)))->~G__TTreeReader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TreeReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TreeReader*) (soff))->~G__TTreeReader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TreeReader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTreeReaderDict {
 public:
  G__Sizep2memfuncTreeReaderDict(): p(&G__Sizep2memfuncTreeReaderDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTreeReaderDict::*p)();
};

size_t G__get_sizep2memfuncTreeReaderDict()
{
  G__Sizep2memfuncTreeReaderDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTreeReaderDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TreeReaderDictLN_TreeReader))) {
     TreeReader *G__Lderived;
     G__Lderived=(TreeReader*)0x1000;
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TreeReaderDictLN_TreeReader),G__get_linked_tagnum(&G__TreeReaderDictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TreeReaderDictLN_TreeReader),G__get_linked_tagnum(&G__TreeReaderDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTreeReaderDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TreeReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__TreeReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__TreeReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TreeReader */
static void G__setup_memvarTreeReader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TreeReaderDictLN_TreeReader));
   { TreeReader *p; p=(TreeReader*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->Run)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Run=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Det)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Det=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T2PrevMu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T2PrevMu=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T2PrevPlMu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T2PrevPlMu=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T2PrevAdMu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T2PrevAdMu=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T2PrevShMu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T2PrevShMu=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T2PrevNetMu)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T2PrevNetMu=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Fold)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Fold=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrigSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigSec[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->TrigNano)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigNano[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->E)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"E[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->X)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"X[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->Y)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Y[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->Z)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Z[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->D2First)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"D2First[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->T2PrevSubEvt)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T2PrevSubEvt[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->TrigSecT)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigSecT[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->TrigNanoT)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigNanoT[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->ET)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"ET[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->XT)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"XT[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->YT)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"YT[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->ZT)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"ZT[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->D2FirstT)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"D2FirstT[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->T2PrevSubEvtT)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T2PrevSubEvtT[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->XCpt)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"XCpt[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->YCpt)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"YCpt[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->ZCpt)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"ZCpt[2]=",0,"[Fold]");
   G__memvar_setup((void*)((long)(&p->b_Run)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_Run=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Det)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_Det=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_T2PrevMu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_T2PrevMu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_T2PrevPlMu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_T2PrevPlMu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_T2PrevAdMu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_T2PrevAdMu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_T2PrevShMu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_T2PrevShMu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_T2PrevNetMu)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_T2PrevNetMu=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Fold)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_Fold=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_TrigSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigNano)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_TrigNano=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_E)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_E=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_X)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_X=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_Y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_Z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D2First)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_D2First=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_T2PrevSubEvt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_T2PrevSubEvt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigSecT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_TrigSecT=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigNanoT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_TrigNanoT=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ET)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_ET=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_XT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_XT=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_YT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_YT=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ZT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_ZT=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_D2FirstT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_D2FirstT=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_T2PrevSubEvtT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_T2PrevSubEvtT=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_XCpt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_XCpt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_YCpt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_YCpt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ZCpt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TBranch),-1,-1,1,"b_ZCpt=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TreeReaderDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTreeReaderDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTreeReader(void) {
   /* TreeReader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TreeReaderDictLN_TreeReader));
   G__memfunc_setup("TreeReader",995,G__TreeReaderDict_534_0_1, 105, G__get_linked_tagnum(&G__TreeReaderDictLN_TreeReader), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Version",742,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Begin",485,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveBegin",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetOption",933,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetObject",899,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputList",1240,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputList",1357,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TreeReaderDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveTerminate",1444,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__TreeReaderDict_534_0_15, 85, G__get_linked_tagnum(&G__TreeReaderDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TreeReader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TreeReaderDict_534_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TreeReader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TreeReaderDict_534_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TreeReader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TreeReaderDict_534_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TreeReader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TreeReaderDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TreeReaderDict_534_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TreeReaderDict_534_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TreeReader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TreeReaderDict_534_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TreeReader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TreeReaderDict_534_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TreeReader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TreeReaderDict_534_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TreeReader::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TreeReader", 1121, G__TreeReaderDict_534_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTreeReaderDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTreeReaderDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTreeReaderDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TreeReaderDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TreeReaderDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__TreeReaderDictLN_TreeReader = { "TreeReader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTreeReaderDict() {
  G__TreeReaderDictLN_TClass.tagnum = -1 ;
  G__TreeReaderDictLN_TBuffer.tagnum = -1 ;
  G__TreeReaderDictLN_TMemberInspector.tagnum = -1 ;
  G__TreeReaderDictLN_TObject.tagnum = -1 ;
  G__TreeReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TreeReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TreeReaderDictLN_TList.tagnum = -1 ;
  G__TreeReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TreeReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TreeReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TreeReaderDictLN_TTree.tagnum = -1 ;
  G__TreeReaderDictLN_TBranch.tagnum = -1 ;
  G__TreeReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__TreeReaderDictLN_TSelector.tagnum = -1 ;
  G__TreeReaderDictLN_TreeReader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTreeReaderDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_TList);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_TSelector);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TreeReaderDictLN_TreeReader),sizeof(TreeReader),-1,29952,(char*)NULL,G__setup_memvarTreeReader,G__setup_memfuncTreeReader);
}
extern "C" void G__cpp_setupTreeReaderDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTreeReaderDict()");
  G__set_cpp_environmentTreeReaderDict();
  G__cpp_setup_tagtableTreeReaderDict();

  G__cpp_setup_inheritanceTreeReaderDict();

  G__cpp_setup_typetableTreeReaderDict();

  G__cpp_setup_memvarTreeReaderDict();

  G__cpp_setup_memfuncTreeReaderDict();
  G__cpp_setup_globalTreeReaderDict();
  G__cpp_setup_funcTreeReaderDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTreeReaderDict();
  return;
}
class G__cpp_setup_initTreeReaderDict {
  public:
    G__cpp_setup_initTreeReaderDict() { G__add_setup_func("TreeReaderDict",(G__incsetup)(&G__cpp_setupTreeReaderDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTreeReaderDict() { G__remove_setup_func("TreeReaderDict"); }
};
G__cpp_setup_initTreeReaderDict G__cpp_setup_initializerTreeReaderDict;

