../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r09.root  MC_LS_r09.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r10.root  MC_LS_r10.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r11.root  MC_LS_r11.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r13.root  MC_LS_r13.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r14.root  MC_LS_r14.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r15.root  MC_LS_r15.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r16.root  MC_LS_r16.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r17.root  MC_LS_r17.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r18.root  MC_LS_r18.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r19.root  MC_LS_r19.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r20.root  MC_LS_r20.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r21.root  MC_LS_r21.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r22.root  MC_LS_r22.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r23.root  MC_LS_r23.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r24.root  MC_LS_r24.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r25.root  MC_LS_r25.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r26.root  MC_LS_r26.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r27.root  MC_LS_r27.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r28.root  MC_LS_r28.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r29.root  MC_LS_r29.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r30.root  MC_LS_r30.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r33.root  MC_LS_r33.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r34.root  MC_LS_r34.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r35.root  MC_LS_r35.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r36.root  MC_LS_r36.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r37.root  MC_LS_r37.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r38.root  MC_LS_r38.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r39.root  MC_LS_r39.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r40.root  MC_LS_r40.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r41.root  MC_LS_r41.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r42.root  MC_LS_r42.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r44.root  MC_LS_r44.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r45.root  MC_LS_r45.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r46.root  MC_LS_r46.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r47.root  MC_LS_r47.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r48.root  MC_LS_r48.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r49.root  MC_LS_r49.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r50.root  MC_LS_r50.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r51.root  MC_LS_r51.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r52.root  MC_LS_r52.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r53.root  MC_LS_r53.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r54.root  MC_LS_r54.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r55.root  MC_LS_r55.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r56.root  MC_LS_r56.TWin.root  RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-LS/MC_LS_r57.root  MC_LS_r57.TWin.root  RunInfo.txt H
