FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_00.root  MC_acrylic_r00.root   00
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_01.root  MC_acrylic_r01.root   01
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_02.root  MC_acrylic_r02.root   02
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_03.root  MC_acrylic_r03.root   03
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_04.root  MC_acrylic_r04.root   04
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_05.root  MC_acrylic_r05.root   05
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_06.root  MC_acrylic_r06.root   06
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_07.root  MC_acrylic_r07.root   07
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_08.root  MC_acrylic_r08.root   08
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_09.root  MC_acrylic_r09.root   09
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_10.root  MC_acrylic_r10.root   10
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_11.root  MC_acrylic_r11.root   11
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_12.root  MC_acrylic_r12.root   12
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_13.root  MC_acrylic_r13.root   13
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_14.root  MC_acrylic_r14.root   14
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_15.root  MC_acrylic_r15.root   15
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_16.root  MC_acrylic_r16.root   16
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_17.root  MC_acrylic_r17.root   17
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_18.root  MC_acrylic_r18.root   18
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_19.root  MC_acrylic_r19.root   19
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_20.root  MC_acrylic_r20.root   20
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_21.root  MC_acrylic_r21.root   21
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_22.root  MC_acrylic_r22.root   22
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_23.root  MC_acrylic_r23.root   23
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_24.root  MC_acrylic_r24.root   24
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_25.root  MC_acrylic_r25.root   25
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_27.root  MC_acrylic_r27.root   27
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_28.root  MC_acrylic_r28.root   28
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_29.root  MC_acrylic_r29.root   29
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_30.root  MC_acrylic_r30.root   30
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_31.root  MC_acrylic_r31.root   31
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_32.root  MC_acrylic_r32.root   32
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_33.root  MC_acrylic_r33.root   33
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_34.root  MC_acrylic_r34.root   34
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_35.root  MC_acrylic_r35.root   35
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_36.root  MC_acrylic_r36.root   36
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_37.root  MC_acrylic_r37.root   37
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_38.root  MC_acrylic_r38.root   38
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_39.root  MC_acrylic_r39.root   39
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_40.root  MC_acrylic_r40.root   40
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_41.root  MC_acrylic_r41.root   41
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_42.root  MC_acrylic_r42.root   42
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_43.root  MC_acrylic_r43.root   43
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_44.root  MC_acrylic_r44.root   44
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_45.root  MC_acrylic_r45.root   45
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_46.root  MC_acrylic_r46.root   46
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_47.root  MC_acrylic_r47.root   47
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_48.root  MC_acrylic_r48.root   48
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_49.root  MC_acrylic_r49.root   49
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_50.root  MC_acrylic_r50.root   50
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_51.root  MC_acrylic_r51.root   51
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_52.root  MC_acrylic_r52.root   52
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_53.root  MC_acrylic_r53.root   53
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_54.root  MC_acrylic_r54.root   54
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_55.root  MC_acrylic_r55.root   55
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_56.root  MC_acrylic_r56.root   56
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_57.root  MC_acrylic_r57.root   57
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_58.root  MC_acrylic_r58.root   58
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_59.root  MC_acrylic_r59.root   59
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_60.root  MC_acrylic_r60.root   60
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_61.root  MC_acrylic_r61.root   61
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_62.root  MC_acrylic_r62.root   62
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_63.root  MC_acrylic_r63.root   63
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_64.root  MC_acrylic_r64.root   64
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_65.root  MC_acrylic_r65.root   65
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_66.root  MC_acrylic_r66.root   66
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_67.root  MC_acrylic_r67.root   67
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_68.root  MC_acrylic_r68.root   68
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_69.root  MC_acrylic_r69.root   69
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_70.root  MC_acrylic_r70.root   70
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_71.root  MC_acrylic_r71.root   71
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_72.root  MC_acrylic_r72.root   72
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_73.root  MC_acrylic_r73.root   73
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_74.root  MC_acrylic_r74.root   74
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_75.root  MC_acrylic_r75.root   75
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_76.root  MC_acrylic_r76.root   76
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_77.root  MC_acrylic_r77.root   77
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_78.root  MC_acrylic_r78.root   78
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_79.root  MC_acrylic_r79.root   79
FastStreamer /back1/dayabay_back1/MC/Rec/IBD-acrylic/Recon_IBD_DYB_AD1_acrylic_80.root  MC_acrylic_r80.root   80

