../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_00.root  MC_LS_BZ_00.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_01.root  MC_LS_BZ_01.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_02.root  MC_LS_BZ_02.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_03.root  MC_LS_BZ_03.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_04.root  MC_LS_BZ_04.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_05.root  MC_LS_BZ_05.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_06.root  MC_LS_BZ_06.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_07.root  MC_LS_BZ_07.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_08.root  MC_LS_BZ_08.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_09.root  MC_LS_BZ_09.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_10.root  MC_LS_BZ_10.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_11.root  MC_LS_BZ_11.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_12.root  MC_LS_BZ_12.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_13.root  MC_LS_BZ_13.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_14.root  MC_LS_BZ_14.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_15.root  MC_LS_BZ_15.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_16.root  MC_LS_BZ_16.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_17.root  MC_LS_BZ_17.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_18.root  MC_LS_BZ_18.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_19.root  MC_LS_BZ_19.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_20.root  MC_LS_BZ_20.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_21.root  MC_LS_BZ_21.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_22.root  MC_LS_BZ_22.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_23.root  MC_LS_BZ_23.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_24.root  MC_LS_BZ_24.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_25.root  MC_LS_BZ_25.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_26.root  MC_LS_BZ_26.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_27.root  MC_LS_BZ_27.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_28.root  MC_LS_BZ_28.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_29.root  MC_LS_BZ_29.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_30.root  MC_LS_BZ_30.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_31.root  MC_LS_BZ_31.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_32.root  MC_LS_BZ_32.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_33.root  MC_LS_BZ_33.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_34.root  MC_LS_BZ_34.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_35.root  MC_LS_BZ_35.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_36.root  MC_LS_BZ_36.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_37.root  MC_LS_BZ_37.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_38.root  MC_LS_BZ_38.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_39.root  MC_LS_BZ_39.TWin.root  RunInfo.txt H
../src/Ostw  /work/dayabay_work/wangzhe/BZ-Sample/Stream/MC_LS_BZ_40.root  MC_LS_BZ_40.TWin.root  RunInfo.txt H
