//
// File generated by rootcint at Tue Mar 20 15:53:36 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME CalibStatsReader_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "CalibStatsReader_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void CalibStatsReader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_CalibStatsReader(void *p = 0);
   static void *newArray_CalibStatsReader(Long_t size, void *p);
   static void delete_CalibStatsReader(void *p);
   static void deleteArray_CalibStatsReader(void *p);
   static void destruct_CalibStatsReader(void *p);
   static void streamer_CalibStatsReader(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::CalibStatsReader*)
   {
      ::CalibStatsReader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::CalibStatsReader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("CalibStatsReader", ::CalibStatsReader::Class_Version(), "./CalibStatsReader.h", 17,
                  typeid(::CalibStatsReader), DefineBehavior(ptr, ptr),
                  &::CalibStatsReader::Dictionary, isa_proxy, 0,
                  sizeof(::CalibStatsReader) );
      instance.SetNew(&new_CalibStatsReader);
      instance.SetNewArray(&newArray_CalibStatsReader);
      instance.SetDelete(&delete_CalibStatsReader);
      instance.SetDeleteArray(&deleteArray_CalibStatsReader);
      instance.SetDestructor(&destruct_CalibStatsReader);
      instance.SetStreamerFunc(&streamer_CalibStatsReader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::CalibStatsReader*)
   {
      return GenerateInitInstanceLocal((::CalibStatsReader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::CalibStatsReader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *CalibStatsReader::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *CalibStatsReader::Class_Name()
{
   return "CalibStatsReader";
}

//______________________________________________________________________________
const char *CalibStatsReader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CalibStatsReader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int CalibStatsReader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::CalibStatsReader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void CalibStatsReader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CalibStatsReader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *CalibStatsReader::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::CalibStatsReader*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void CalibStatsReader::Streamer(TBuffer &R__b)
{
   // Stream an object of class CalibStatsReader.

   TSelector::Streamer(R__b);
}

//______________________________________________________________________________
void CalibStatsReader::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class CalibStatsReader.
      TClass *R__cl = ::CalibStatsReader::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "clID", &clID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "earliest_mSec", &earliest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "earliest_mNanoSec", &earliest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "latest_mSec", &latest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "latest_mNanoSec", &latest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mSite", &context_mSite);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mSimFlag", &context_mSimFlag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mTimeStamp_mSec", &context_mTimeStamp_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mTimeStamp_mNanoSec", &context_mTimeStamp_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "context_mDetId", &context_mDetId);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "execNumber", &execNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "jobId_m_data[4]", jobId_m_data);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "randomState", (void*)&randomState);
      R__insp.InspectMember("vector<unsigned long>", (void*)&randomState, "randomState.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputHeaders_", &inputHeaders_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputHeaders_m_entry[1]", inputHeaders_m_entry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputHeaders_m_path[1]", inputHeaders_m_path);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ColumnKurtosis", &ColumnKurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Column_2inchPMT", &Column_2inchPMT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ELast_ADCalibShower_pe", &ELast_ADCalibShower_pe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ELast_ADShower_pe", &ELast_ADShower_pe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EarlyCharge", &EarlyCharge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Kurtosis", &Kurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "LateCharge", &LateCharge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MainPeakRMS", &MainPeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MaxQ", &MaxQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MaxQ_2inchPMT", &MaxQ_2inchPMT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MiddleTimeRMS", &MiddleTimeRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NominalCharge", &NominalCharge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PeakRMS", &PeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Q1", &Q1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Q2", &Q2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Q3", &Q3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Quadrant", &Quadrant);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QuadrantQ1", &QuadrantQ1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QuadrantQ2", &QuadrantQ2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QuadrantQ3", &QuadrantQ3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QuadrantQ4", &QuadrantQ4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RingKurtosis", &RingKurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SecondPeakRMS", &SecondPeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "blocked_trigger", &blocked_trigger);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "buffer_full_flag", &buffer_full_flag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_sum_flasher_max", &charge_sum_flasher_max);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLastAD1_ms", &dtLastAD1_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLastAD2_ms", &dtLastAD2_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLastAD3_ms", &dtLastAD3_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLastAD4_ms", &dtLastAD4_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLastIWS_ms", &dtLastIWS_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLastOWS_ms", &dtLastOWS_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLastRPC_ms", &dtLastRPC_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLast_ADCalibShower_ms", &dtLast_ADCalibShower_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLast_ADMuon_ms", &dtLast_ADMuon_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtLast_ADShower_ms", &dtLast_ADShower_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtNextAD1_ms", &dtNextAD1_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtNextAD2_ms", &dtNextAD2_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtNextAD3_ms", &dtNextAD3_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtNextAD4_ms", &dtNextAD4_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtNextIWS_ms", &dtNextIWS_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtNextOWS_ms", &dtNextOWS_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dtNextRPC_ms", &dtNextRPC_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "flasher_column", &flasher_column);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "flasher_flag", &flasher_flag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "flasher_ring", &flasher_ring);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "integralLiveTime_blocked_trigger_ms", &integralLiveTime_blocked_trigger_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "integralLiveTime_buffer_full_ms", &integralLiveTime_buffer_full_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "integralRunTime_ms", &integralRunTime_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "maxqCol", &maxqCol);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "maxqRing", &maxqRing);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nCalibPESum", &nCalibPESum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nHit", &nHit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPEMax", &nPEMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPEMedian", &nPEMedian);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPERMS", &nPERMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPESum", &nPESum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPulseMedian", &nPulseMedian);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPulseRMS", &nPulseRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPulseSum", &nPulseSum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tEarliest", &tEarliest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tLatest", &tLatest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tMean", &tMean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tMedian", &tMedian);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tRMS", &tRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "time_PSD", &time_PSD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "time_PSD1", &time_PSD1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "time_PSD_local_RMS", &time_PSD_local_RMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "triggerNumber", &triggerNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_clID", &b_Data_CalibStats_clID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_earliest_mSec", &b_Data_CalibStats_earliest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_earliest_mNanoSec", &b_Data_CalibStats_earliest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_latest_mSec", &b_Data_CalibStats_latest_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_latest_mNanoSec", &b_Data_CalibStats_latest_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_context_mSite", &b_Data_CalibStats_context_mSite);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_context_mSimFlag", &b_Data_CalibStats_context_mSimFlag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_context_mTimeStamp_mSec", &b_Data_CalibStats_context_mTimeStamp_mSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_context_mTimeStamp_mNanoSec", &b_Data_CalibStats_context_mTimeStamp_mNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_context_mDetId", &b_Data_CalibStats_context_mDetId);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_execNumber", &b_Data_CalibStats_execNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_jobId_m_data", &b_Data_CalibStats_jobId_m_data);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_randomState", &b_Data_CalibStats_randomState);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Data_CalibStats_inputHeaders_", &b_Data_CalibStats_inputHeaders_);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_inputHeaders_m_entry", &b_inputHeaders_m_entry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_inputHeaders_m_path", &b_inputHeaders_m_path);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ColumnKurtosis", &b_ColumnKurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Column_2inchPMT", &b_Column_2inchPMT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ELast_ADCalibShower_pe", &b_ELast_ADCalibShower_pe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ELast_ADShower_pe", &b_ELast_ADShower_pe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_EarlyCharge", &b_EarlyCharge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Kurtosis", &b_Kurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_LateCharge", &b_LateCharge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MainPeakRMS", &b_MainPeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MaxQ", &b_MaxQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MaxQ_2inchPMT", &b_MaxQ_2inchPMT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MiddleTimeRMS", &b_MiddleTimeRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_NominalCharge", &b_NominalCharge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_PeakRMS", &b_PeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Q1", &b_Q1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Q2", &b_Q2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Q3", &b_Q3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Quadrant", &b_Quadrant);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_QuadrantQ1", &b_QuadrantQ1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_QuadrantQ2", &b_QuadrantQ2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_QuadrantQ3", &b_QuadrantQ3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_QuadrantQ4", &b_QuadrantQ4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_RingKurtosis", &b_RingKurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_SecondPeakRMS", &b_SecondPeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_blocked_trigger", &b_blocked_trigger);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_buffer_full_flag", &b_buffer_full_flag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_charge_sum_flasher_max", &b_charge_sum_flasher_max);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLastAD1_ms", &b_dtLastAD1_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLastAD2_ms", &b_dtLastAD2_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLastAD3_ms", &b_dtLastAD3_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLastAD4_ms", &b_dtLastAD4_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLastIWS_ms", &b_dtLastIWS_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLastOWS_ms", &b_dtLastOWS_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLastRPC_ms", &b_dtLastRPC_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLast_ADCalibShower_ms", &b_dtLast_ADCalibShower_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLast_ADMuon_ms", &b_dtLast_ADMuon_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtLast_ADShower_ms", &b_dtLast_ADShower_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtNextAD1_ms", &b_dtNextAD1_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtNextAD2_ms", &b_dtNextAD2_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtNextAD3_ms", &b_dtNextAD3_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtNextAD4_ms", &b_dtNextAD4_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtNextIWS_ms", &b_dtNextIWS_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtNextOWS_ms", &b_dtNextOWS_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dtNextRPC_ms", &b_dtNextRPC_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_flasher_column", &b_flasher_column);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_flasher_flag", &b_flasher_flag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_flasher_ring", &b_flasher_ring);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_integralLiveTime_blocked_trigger_ms", &b_integralLiveTime_blocked_trigger_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_integralLiveTime_buffer_full_ms", &b_integralLiveTime_buffer_full_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_integralRunTime_ms", &b_integralRunTime_ms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_maxqCol", &b_maxqCol);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_maxqRing", &b_maxqRing);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nCalibPESum", &b_nCalibPESum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nHit", &b_nHit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nPEMax", &b_nPEMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nPEMedian", &b_nPEMedian);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nPERMS", &b_nPERMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nPESum", &b_nPESum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nPulseMedian", &b_nPulseMedian);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nPulseRMS", &b_nPulseRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nPulseSum", &b_nPulseSum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_tEarliest", &b_tEarliest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_tLatest", &b_tLatest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_tMean", &b_tMean);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_tMedian", &b_tMedian);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_tRMS", &b_tRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_time_PSD", &b_time_PSD);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_time_PSD1", &b_time_PSD1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_time_PSD_local_RMS", &b_time_PSD_local_RMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_triggerNumber", &b_triggerNumber);
      TSelector::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_CalibStatsReader(void *p) {
      return  p ? new(p) ::CalibStatsReader : new ::CalibStatsReader;
   }
   static void *newArray_CalibStatsReader(Long_t nElements, void *p) {
      return p ? new(p) ::CalibStatsReader[nElements] : new ::CalibStatsReader[nElements];
   }
   // Wrapper around operator delete
   static void delete_CalibStatsReader(void *p) {
      delete ((::CalibStatsReader*)p);
   }
   static void deleteArray_CalibStatsReader(void *p) {
      delete [] ((::CalibStatsReader*)p);
   }
   static void destruct_CalibStatsReader(void *p) {
      typedef ::CalibStatsReader current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_CalibStatsReader(TBuffer &buf, void *obj) {
      ((::CalibStatsReader*)obj)->::CalibStatsReader::Streamer(buf);
   }
} // end of namespace ROOT for class ::CalibStatsReader

/********************************************************
* CalibStatsReader_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableCalibStatsReader_Dict();

extern "C" void G__set_cpp_environmentCalibStatsReader_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("CalibStatsReader.h");
  G__cpp_reset_tagtableCalibStatsReader_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevCalibStatsReader_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* CalibStatsReader */
static int G__CalibStatsReader_Dict_534_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   CalibStatsReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new CalibStatsReader((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) CalibStatsReader((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new CalibStatsReader[n];
       } else {
         p = new((void*) gvp) CalibStatsReader[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new CalibStatsReader;
       } else {
         p = new((void*) gvp) CalibStatsReader;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_CalibStatsReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibStatsReader_Dict_534_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) CalibStatsReader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibStatsReader_Dict_534_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CalibStatsReader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibStatsReader_Dict_534_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) CalibStatsReader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibStatsReader_Dict_534_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      CalibStatsReader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibStatsReader_Dict_534_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((CalibStatsReader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibStatsReader_Dict_534_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CalibStatsReader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibStatsReader_Dict_534_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CalibStatsReader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibStatsReader_Dict_534_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) CalibStatsReader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__CalibStatsReader_Dict_534_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) CalibStatsReader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef CalibStatsReader G__TCalibStatsReader;
static int G__CalibStatsReader_Dict_534_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (CalibStatsReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((CalibStatsReader*) (soff+(sizeof(CalibStatsReader)*i)))->~G__TCalibStatsReader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (CalibStatsReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((CalibStatsReader*) (soff))->~G__TCalibStatsReader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* CalibStatsReader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncCalibStatsReader_Dict {
 public:
  G__Sizep2memfuncCalibStatsReader_Dict(): p(&G__Sizep2memfuncCalibStatsReader_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncCalibStatsReader_Dict::*p)();
};

size_t G__get_sizep2memfuncCalibStatsReader_Dict()
{
  G__Sizep2memfuncCalibStatsReader_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceCalibStatsReader_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__CalibStatsReader_DictLN_CalibStatsReader))) {
     CalibStatsReader *G__Lderived;
     G__Lderived=(CalibStatsReader*)0x1000;
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CalibStatsReader_DictLN_CalibStatsReader),G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__CalibStatsReader_DictLN_CalibStatsReader),G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableCalibStatsReader_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* CalibStatsReader */
static void G__setup_memvarCalibStatsReader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__CalibStatsReader_DictLN_CalibStatsReader));
   { CalibStatsReader *p; p=(CalibStatsReader*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->clID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"clID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->earliest_mSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"earliest_mSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->earliest_mNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"earliest_mNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->latest_mSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"latest_mSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->latest_mNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"latest_mNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mSite)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mSite=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mSimFlag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mSimFlag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mTimeStamp_mSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mTimeStamp_mSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mTimeStamp_mNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mTimeStamp_mNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->context_mDetId)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"context_mDetId=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->execNumber)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"execNumber=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->jobId_m_data)-(long)(p)),104,0,0,-1,G__defined_typename("UInt_t"),-1,1,"jobId_m_data[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->randomState)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR),G__defined_typename("vector<unsigned long>"),-1,1,"randomState=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->inputHeaders_)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"inputHeaders_=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->inputHeaders_m_entry)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"inputHeaders_m_entry[1]=",0,"[inputHeaders_]");
   G__memvar_setup((void*)((long)(&p->inputHeaders_m_path)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_string),-1,-1,1,"inputHeaders_m_path[1]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ColumnKurtosis)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ColumnKurtosis=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Column_2inchPMT)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Column_2inchPMT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ELast_ADCalibShower_pe)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ELast_ADCalibShower_pe=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ELast_ADShower_pe)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ELast_ADShower_pe=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EarlyCharge)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"EarlyCharge=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Kurtosis)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Kurtosis=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->LateCharge)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"LateCharge=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MainPeakRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MainPeakRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MaxQ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MaxQ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MaxQ_2inchPMT)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MaxQ_2inchPMT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MiddleTimeRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MiddleTimeRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NominalCharge)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"NominalCharge=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PeakRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PeakRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Q1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Q1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Q2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Q2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Q3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Q3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Quadrant)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Quadrant=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QuadrantQ1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"QuadrantQ1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QuadrantQ2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"QuadrantQ2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QuadrantQ3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"QuadrantQ3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QuadrantQ4)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"QuadrantQ4=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->RingKurtosis)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"RingKurtosis=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SecondPeakRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"SecondPeakRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->blocked_trigger)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"blocked_trigger=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->buffer_full_flag)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"buffer_full_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->charge_sum_flasher_max)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"charge_sum_flasher_max=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLastAD1_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtLastAD1_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLastAD2_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtLastAD2_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLastAD3_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtLastAD3_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLastAD4_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtLastAD4_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLastIWS_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtLastIWS_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLastOWS_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtLastOWS_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLastRPC_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtLastRPC_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLast_ADCalibShower_ms)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"dtLast_ADCalibShower_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLast_ADMuon_ms)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"dtLast_ADMuon_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtLast_ADShower_ms)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"dtLast_ADShower_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtNextAD1_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtNextAD1_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtNextAD2_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtNextAD2_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtNextAD3_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtNextAD3_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtNextAD4_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtNextAD4_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtNextIWS_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtNextIWS_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtNextOWS_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtNextOWS_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtNextRPC_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dtNextRPC_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->flasher_column)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"flasher_column=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->flasher_flag)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"flasher_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->flasher_ring)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"flasher_ring=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->integralLiveTime_blocked_trigger_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"integralLiveTime_blocked_trigger_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->integralLiveTime_buffer_full_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"integralLiveTime_buffer_full_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->integralRunTime_ms)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"integralRunTime_ms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->maxqCol)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"maxqCol=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->maxqRing)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"maxqRing=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nCalibPESum)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"nCalibPESum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nHit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nHit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nPEMax)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"nPEMax=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nPEMedian)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"nPEMedian=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nPERMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"nPERMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nPESum)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"nPESum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nPulseMedian)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"nPulseMedian=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nPulseRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"nPulseRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nPulseSum)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"nPulseSum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tEarliest)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tEarliest=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tLatest)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tLatest=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tMean)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tMean=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tMedian)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tMedian=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->time_PSD)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"time_PSD=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->time_PSD1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"time_PSD1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->time_PSD_local_RMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"time_PSD_local_RMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerNumber)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"triggerNumber=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_clID)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_clID=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_earliest_mSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_earliest_mSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_earliest_mNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_earliest_mNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_latest_mSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_latest_mSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_latest_mNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_latest_mNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_context_mSite)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_context_mSite=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_context_mSimFlag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_context_mSimFlag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_context_mTimeStamp_mSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_context_mTimeStamp_mSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_context_mTimeStamp_mNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_context_mTimeStamp_mNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_context_mDetId)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_context_mDetId=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_execNumber)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_execNumber=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_jobId_m_data)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_jobId_m_data=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_randomState)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_randomState=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Data_CalibStats_inputHeaders_)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Data_CalibStats_inputHeaders_=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_inputHeaders_m_entry)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_inputHeaders_m_entry=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_inputHeaders_m_path)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_inputHeaders_m_path=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ColumnKurtosis)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_ColumnKurtosis=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Column_2inchPMT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Column_2inchPMT=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ELast_ADCalibShower_pe)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_ELast_ADCalibShower_pe=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ELast_ADShower_pe)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_ELast_ADShower_pe=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_EarlyCharge)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_EarlyCharge=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Kurtosis)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Kurtosis=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_LateCharge)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_LateCharge=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MainPeakRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_MainPeakRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MaxQ)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_MaxQ=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MaxQ_2inchPMT)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_MaxQ_2inchPMT=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MiddleTimeRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_MiddleTimeRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_NominalCharge)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_NominalCharge=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PeakRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_PeakRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Q1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Q1=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Q2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Q2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Q3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Q3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Quadrant)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_Quadrant=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_QuadrantQ1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_QuadrantQ1=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_QuadrantQ2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_QuadrantQ2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_QuadrantQ3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_QuadrantQ3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_QuadrantQ4)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_QuadrantQ4=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_RingKurtosis)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_RingKurtosis=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_SecondPeakRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_SecondPeakRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_blocked_trigger)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_blocked_trigger=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_buffer_full_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_buffer_full_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_charge_sum_flasher_max)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_charge_sum_flasher_max=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLastAD1_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLastAD1_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLastAD2_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLastAD2_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLastAD3_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLastAD3_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLastAD4_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLastAD4_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLastIWS_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLastIWS_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLastOWS_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLastOWS_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLastRPC_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLastRPC_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLast_ADCalibShower_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLast_ADCalibShower_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLast_ADMuon_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLast_ADMuon_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtLast_ADShower_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtLast_ADShower_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtNextAD1_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtNextAD1_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtNextAD2_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtNextAD2_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtNextAD3_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtNextAD3_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtNextAD4_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtNextAD4_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtNextIWS_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtNextIWS_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtNextOWS_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtNextOWS_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dtNextRPC_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_dtNextRPC_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_flasher_column)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_flasher_column=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_flasher_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_flasher_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_flasher_ring)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_flasher_ring=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_integralLiveTime_blocked_trigger_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_integralLiveTime_blocked_trigger_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_integralLiveTime_buffer_full_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_integralLiveTime_buffer_full_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_integralRunTime_ms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_integralRunTime_ms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_maxqCol)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_maxqCol=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_maxqRing)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_maxqRing=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nCalibPESum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_nCalibPESum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nHit)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_nHit=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nPEMax)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_nPEMax=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nPEMedian)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_nPEMedian=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nPERMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_nPERMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nPESum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_nPESum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nPulseMedian)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_nPulseMedian=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nPulseRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_nPulseRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nPulseSum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_nPulseSum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tEarliest)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_tEarliest=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tLatest)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_tLatest=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tMean)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_tMean=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tMedian)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_tMedian=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_tRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_time_PSD)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_time_PSD=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_time_PSD1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_time_PSD1=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_time_PSD_local_RMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_time_PSD_local_RMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_triggerNumber)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TBranch),-1,-1,1,"b_triggerNumber=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarCalibStatsReader_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCalibStatsReader(void) {
   /* CalibStatsReader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__CalibStatsReader_DictLN_CalibStatsReader));
   G__memfunc_setup("CalibStatsReader",1597,G__CalibStatsReader_Dict_534_0_1, 105, G__get_linked_tagnum(&G__CalibStatsReader_DictLN_CalibStatsReader), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Version",742,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Begin",485,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveBegin",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetOption",933,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetObject",899,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputList",1240,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputList",1357,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveTerminate",1444,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__CalibStatsReader_Dict_534_0_15, 85, G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&CalibStatsReader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__CalibStatsReader_Dict_534_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CalibStatsReader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__CalibStatsReader_Dict_534_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&CalibStatsReader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__CalibStatsReader_Dict_534_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&CalibStatsReader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__CalibStatsReader_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__CalibStatsReader_Dict_534_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__CalibStatsReader_Dict_534_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CalibStatsReader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__CalibStatsReader_Dict_534_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CalibStatsReader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__CalibStatsReader_Dict_534_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&CalibStatsReader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__CalibStatsReader_Dict_534_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&CalibStatsReader::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~CalibStatsReader", 1723, G__CalibStatsReader_Dict_534_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncCalibStatsReader_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalCalibStatsReader_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcCalibStatsReader_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__CalibStatsReader_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR = { "vector<unsigned long,allocator<unsigned long> >" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__CalibStatsReader_DictLN_CalibStatsReader = { "CalibStatsReader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableCalibStatsReader_Dict() {
  G__CalibStatsReader_DictLN_TClass.tagnum = -1 ;
  G__CalibStatsReader_DictLN_TBuffer.tagnum = -1 ;
  G__CalibStatsReader_DictLN_TMemberInspector.tagnum = -1 ;
  G__CalibStatsReader_DictLN_TObject.tagnum = -1 ;
  G__CalibStatsReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR.tagnum = -1 ;
  G__CalibStatsReader_DictLN_string.tagnum = -1 ;
  G__CalibStatsReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CalibStatsReader_DictLN_TList.tagnum = -1 ;
  G__CalibStatsReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__CalibStatsReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__CalibStatsReader_DictLN_TTree.tagnum = -1 ;
  G__CalibStatsReader_DictLN_TBranch.tagnum = -1 ;
  G__CalibStatsReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__CalibStatsReader_DictLN_TSelector.tagnum = -1 ;
  G__CalibStatsReader_DictLN_CalibStatsReader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableCalibStatsReader_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_string);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_TList);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_TTree);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_TSelector);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__CalibStatsReader_DictLN_CalibStatsReader),sizeof(CalibStatsReader),-1,29952,(char*)NULL,G__setup_memvarCalibStatsReader,G__setup_memfuncCalibStatsReader);
}
extern "C" void G__cpp_setupCalibStatsReader_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupCalibStatsReader_Dict()");
  G__set_cpp_environmentCalibStatsReader_Dict();
  G__cpp_setup_tagtableCalibStatsReader_Dict();

  G__cpp_setup_inheritanceCalibStatsReader_Dict();

  G__cpp_setup_typetableCalibStatsReader_Dict();

  G__cpp_setup_memvarCalibStatsReader_Dict();

  G__cpp_setup_memfuncCalibStatsReader_Dict();
  G__cpp_setup_globalCalibStatsReader_Dict();
  G__cpp_setup_funcCalibStatsReader_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncCalibStatsReader_Dict();
  return;
}
class G__cpp_setup_initCalibStatsReader_Dict {
  public:
    G__cpp_setup_initCalibStatsReader_Dict() { G__add_setup_func("CalibStatsReader_Dict",(G__incsetup)(&G__cpp_setupCalibStatsReader_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initCalibStatsReader_Dict() { G__remove_setup_func("CalibStatsReader_Dict"); }
};
G__cpp_setup_initCalibStatsReader_Dict G__cpp_setup_initializerCalibStatsReader_Dict;

