/********************************************************************
* TreeReaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TreeReaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTreeReaderDict();
extern void G__cpp_setup_inheritanceTreeReaderDict();
extern void G__cpp_setup_typetableTreeReaderDict();
extern void G__cpp_setup_memvarTreeReaderDict();
extern void G__cpp_setup_globalTreeReaderDict();
extern void G__cpp_setup_memfuncTreeReaderDict();
extern void G__cpp_setup_funcTreeReaderDict();
extern void G__set_cpp_environmentTreeReaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TreeReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TreeReaderDictLN_TClass;
extern G__linked_taginfo G__TreeReaderDictLN_TBuffer;
extern G__linked_taginfo G__TreeReaderDictLN_TMemberInspector;
extern G__linked_taginfo G__TreeReaderDictLN_TObject;
extern G__linked_taginfo G__TreeReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TreeReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeReaderDictLN_TList;
extern G__linked_taginfo G__TreeReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TreeReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TreeReaderDictLN_TTree;
extern G__linked_taginfo G__TreeReaderDictLN_TBranch;
extern G__linked_taginfo G__TreeReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TreeReaderDictLN_TSelector;
extern G__linked_taginfo G__TreeReaderDictLN_TreeReader;

/* STUB derived class for protected member access */
