/********************************************************************
* CalibReadoutHeaderReader_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CalibReadoutHeaderReader_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCalibReadoutHeaderReader_Dict();
extern void G__cpp_setup_inheritanceCalibReadoutHeaderReader_Dict();
extern void G__cpp_setup_typetableCalibReadoutHeaderReader_Dict();
extern void G__cpp_setup_memvarCalibReadoutHeaderReader_Dict();
extern void G__cpp_setup_globalCalibReadoutHeaderReader_Dict();
extern void G__cpp_setup_memfuncCalibReadoutHeaderReader_Dict();
extern void G__cpp_setup_funcCalibReadoutHeaderReader_Dict();
extern void G__set_cpp_environmentCalibReadoutHeaderReader_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CalibReadoutHeaderReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TClass;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TBuffer;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TMemberInspector;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TObject;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_string;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TList;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TTree;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TBranch;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_TSelector;
extern G__linked_taginfo G__CalibReadoutHeaderReader_DictLN_CalibReadoutHeaderReader;

/* STUB derived class for protected member access */
