//
// File generated by rootcint at Mon Nov 21 10:59:43 2011

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME Tree2Selectordict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Tree2Selectordict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Tree2Selector_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_Tree2Selector(void *p = 0);
   static void *newArray_Tree2Selector(Long_t size, void *p);
   static void delete_Tree2Selector(void *p);
   static void deleteArray_Tree2Selector(void *p);
   static void destruct_Tree2Selector(void *p);
   static void streamer_Tree2Selector(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Tree2Selector*)
   {
      ::Tree2Selector *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Tree2Selector >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Tree2Selector", ::Tree2Selector::Class_Version(), "./Tree2Selector.h", 16,
                  typeid(::Tree2Selector), DefineBehavior(ptr, ptr),
                  &::Tree2Selector::Dictionary, isa_proxy, 0,
                  sizeof(::Tree2Selector) );
      instance.SetNew(&new_Tree2Selector);
      instance.SetNewArray(&newArray_Tree2Selector);
      instance.SetDelete(&delete_Tree2Selector);
      instance.SetDeleteArray(&deleteArray_Tree2Selector);
      instance.SetDestructor(&destruct_Tree2Selector);
      instance.SetStreamerFunc(&streamer_Tree2Selector);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Tree2Selector*)
   {
      return GenerateInitInstanceLocal((::Tree2Selector*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Tree2Selector*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *Tree2Selector::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *Tree2Selector::Class_Name()
{
   return "Tree2Selector";
}

//______________________________________________________________________________
const char *Tree2Selector::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Tree2Selector*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Tree2Selector::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Tree2Selector*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Tree2Selector::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Tree2Selector*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Tree2Selector::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Tree2Selector*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void Tree2Selector::Streamer(TBuffer &R__b)
{
   // Stream an object of class Tree2Selector.

   TSelector::Streamer(R__b);
}

//______________________________________________________________________________
void Tree2Selector::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Tree2Selector.
      TClass *R__cl = ::Tree2Selector::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Run", &Run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Event", &Event);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ExecNum", &ExecNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Site", &Site);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Det", &Det);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigType", &TrigType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigSec", &TrigSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigNanoSec", &TrigNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Status", &Status);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Energy", &Energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "X", &X);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Y", &Y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Z", &Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MLEnergy", &MLEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MLX", &MLX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MLY", &MLY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MLZ", &MLZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Px", &Px);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Py", &Py);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Pz", &Pz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ScaledEnergy", &ScaledEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ScaledX", &ScaledX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ScaledY", &ScaledY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ScaledZ", &ScaledZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NPmt", &NPmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PERMS", &PERMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PESum", &PESum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TimeRMS", &TimeRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RatioMaxQ", &RatioMaxQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EarlyChargeSum", &EarlyChargeSum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MiddleChargeSum", &MiddleChargeSum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "LateChargeSum", &LateChargeSum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EffNPmt", &EffNPmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EffPERMS", &EffPERMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EffPESum", &EffPESum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EffTimeRMS", &EffTimeRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EffRatioMaxQ", &EffRatioMaxQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EffRatioMaxQ123", &EffRatioMaxQ123);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "EffRatioMaxQ3x3", &EffRatioMaxQ3x3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MiddleTimeRMS", &MiddleTimeRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MaxQ", &MaxQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Quadrant", &Quadrant);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "PeakRMS", &PeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Kurtosis", &Kurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QuadrantQ1", &QuadrantQ1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QuadrantQ2", &QuadrantQ2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QuadrantQ3", &QuadrantQ3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QuadrantQ4", &QuadrantQ4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RingKurtosis", &RingKurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ColumnKurtosis", &ColumnKurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MainPeakRMS", &MainPeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SecondPeakRMS", &SecondPeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_sum_flasher_flag", &charge_sum_flasher_flag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge_sum_flasher_max", &charge_sum_flasher_max);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "flasher_ring", &flasher_ring);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "flasher_column", &flasher_column);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tRMS_local", &tRMS_local);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tRMS_local_wo_1st_hit", &tRMS_local_wo_1st_hit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Run", &b_Run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Event", &b_Event);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ExecNum", &b_ExecNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Site", &b_Site);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Det", &b_Det);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigType", &b_TrigType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigSec", &b_TrigSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigNanoSec", &b_TrigNanoSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Status", &b_Status);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Energy", &b_Energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_X", &b_X);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Y", &b_Y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Z", &b_Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MLEnergy", &b_MLEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MLX", &b_MLX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MLY", &b_MLY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MLZ", &b_MLZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Px", &b_Px);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Py", &b_Py);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Pz", &b_Pz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ScaledEnergy", &b_ScaledEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ScaledX", &b_ScaledX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ScaledY", &b_ScaledY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ScaledZ", &b_ScaledZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_NPmt", &b_NPmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_PERMS", &b_PERMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_PESum", &b_PESum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TimeRMS", &b_TimeRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_RatioMaxQ", &b_RatioMaxQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_EarlyChargeSum", &b_EarlyChargeSum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MiddleChargeSum", &b_MiddleChargeSum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_LateChargeSum", &b_LateChargeSum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_EffNPmt", &b_EffNPmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_EffPERMS", &b_EffPERMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_EffPESum", &b_EffPESum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_EffTimeRMS", &b_EffTimeRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_EffRatioMaxQ", &b_EffRatioMaxQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_EffRatioMaxQ123", &b_EffRatioMaxQ123);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_EffRatioMaxQ3x3", &b_EffRatioMaxQ3x3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MiddleTimeRMS", &b_MiddleTimeRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MaxQ", &b_MaxQ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Quadrant", &b_Quadrant);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_PeakRMS", &b_PeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Kurtosis", &b_Kurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_QuadrantQ1", &b_QuadrantQ1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_QuadrantQ2", &b_QuadrantQ2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_QuadrantQ3", &b_QuadrantQ3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_QuadrantQ4", &b_QuadrantQ4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_RingKurtosis", &b_RingKurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ColumnKurtosis", &b_ColumnKurtosis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MainPeakRMS", &b_MainPeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_SecondPeakRMS", &b_SecondPeakRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_charge_sum_flasher_flag", &b_charge_sum_flasher_flag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_charge_sum_flasher_max", &b_charge_sum_flasher_max);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_flasher_ring", &b_flasher_ring);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_flasher_column", &b_flasher_column);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_tRMS_local", &b_tRMS_local);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_tRMS_local_wo_1st_hit", &b_tRMS_local_wo_1st_hit);
      TSelector::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Tree2Selector(void *p) {
      return  p ? new(p) ::Tree2Selector : new ::Tree2Selector;
   }
   static void *newArray_Tree2Selector(Long_t nElements, void *p) {
      return p ? new(p) ::Tree2Selector[nElements] : new ::Tree2Selector[nElements];
   }
   // Wrapper around operator delete
   static void delete_Tree2Selector(void *p) {
      delete ((::Tree2Selector*)p);
   }
   static void deleteArray_Tree2Selector(void *p) {
      delete [] ((::Tree2Selector*)p);
   }
   static void destruct_Tree2Selector(void *p) {
      typedef ::Tree2Selector current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_Tree2Selector(TBuffer &buf, void *obj) {
      ((::Tree2Selector*)obj)->::Tree2Selector::Streamer(buf);
   }
} // end of namespace ROOT for class ::Tree2Selector

/********************************************************
* Tree2Selectordict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTree2Selectordict();

extern "C" void G__set_cpp_environmentTree2Selectordict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Tree2Selector.h");
  G__cpp_reset_tagtableTree2Selectordict();
}
#include <new>
extern "C" int G__cpp_dllrevTree2Selectordict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Tree2Selector */
static int G__Tree2Selectordict_534_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Tree2Selector* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Tree2Selector((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) Tree2Selector((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new Tree2Selector[n];
       } else {
         p = new((void*) gvp) Tree2Selector[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new Tree2Selector;
       } else {
         p = new((void*) gvp) Tree2Selector;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Tree2SelectordictLN_Tree2Selector));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Tree2Selectordict_534_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Tree2Selector::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Tree2Selectordict_534_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Tree2Selector::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Tree2Selectordict_534_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Tree2Selector::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Tree2Selectordict_534_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Tree2Selector::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Tree2Selectordict_534_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Tree2Selector*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Tree2Selectordict_534_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Tree2Selector::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Tree2Selectordict_534_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Tree2Selector::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Tree2Selectordict_534_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Tree2Selector::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Tree2Selectordict_534_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Tree2Selector::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Tree2Selector G__TTree2Selector;
static int G__Tree2Selectordict_534_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Tree2Selector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Tree2Selector*) (soff+(sizeof(Tree2Selector)*i)))->~G__TTree2Selector();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Tree2Selector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Tree2Selector*) (soff))->~G__TTree2Selector();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Tree2Selector */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTree2Selectordict {
 public:
  G__Sizep2memfuncTree2Selectordict(): p(&G__Sizep2memfuncTree2Selectordict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTree2Selectordict::*p)();
};

size_t G__get_sizep2memfuncTree2Selectordict()
{
  G__Sizep2memfuncTree2Selectordict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTree2Selectordict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Tree2SelectordictLN_Tree2Selector))) {
     Tree2Selector *G__Lderived;
     G__Lderived=(Tree2Selector*)0x1000;
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Tree2SelectordictLN_Tree2Selector),G__get_linked_tagnum(&G__Tree2SelectordictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Tree2SelectordictLN_Tree2Selector),G__get_linked_tagnum(&G__Tree2SelectordictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTree2Selectordict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Tree2SelectordictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Tree2SelectordictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Tree2SelectordictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Tree2SelectordictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__Tree2SelectordictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Tree2Selector */
static void G__setup_memvarTree2Selector(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Tree2SelectordictLN_Tree2Selector));
   { Tree2Selector *p; p=(Tree2Selector*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->Run)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Run=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Event)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Event=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ExecNum)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ExecNum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Site)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Site=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Det)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Det=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrigType)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigType=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrigSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrigNanoSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigNanoSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Status)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Status=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Energy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Energy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->X)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"X=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MLEnergy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MLEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MLX)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MLX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MLY)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MLY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MLZ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MLZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Px)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Px=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Py)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Py=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Pz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Pz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ScaledEnergy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ScaledEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ScaledX)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ScaledX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ScaledY)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ScaledY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ScaledZ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ScaledZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NPmt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"NPmt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PERMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PERMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PESum)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PESum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TimeRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"TimeRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->RatioMaxQ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"RatioMaxQ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EarlyChargeSum)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"EarlyChargeSum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MiddleChargeSum)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MiddleChargeSum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->LateChargeSum)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"LateChargeSum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EffNPmt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"EffNPmt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EffPERMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"EffPERMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EffPESum)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"EffPESum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EffTimeRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"EffTimeRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EffRatioMaxQ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"EffRatioMaxQ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EffRatioMaxQ123)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"EffRatioMaxQ123=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->EffRatioMaxQ3x3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"EffRatioMaxQ3x3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MiddleTimeRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MiddleTimeRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MaxQ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MaxQ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Quadrant)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Quadrant=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->PeakRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"PeakRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Kurtosis)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"Kurtosis=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QuadrantQ1)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"QuadrantQ1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QuadrantQ2)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"QuadrantQ2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QuadrantQ3)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"QuadrantQ3=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QuadrantQ4)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"QuadrantQ4=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->RingKurtosis)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"RingKurtosis=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ColumnKurtosis)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ColumnKurtosis=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MainPeakRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"MainPeakRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SecondPeakRMS)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"SecondPeakRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->charge_sum_flasher_flag)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"charge_sum_flasher_flag=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->charge_sum_flasher_max)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"charge_sum_flasher_max=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->flasher_ring)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"flasher_ring=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->flasher_column)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"flasher_column=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tRMS_local)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tRMS_local=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tRMS_local_wo_1st_hit)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tRMS_local_wo_1st_hit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_Run)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Run=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Event)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Event=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ExecNum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_ExecNum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Site)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Site=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Det)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Det=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigType)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_TrigType=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_TrigSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigNanoSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_TrigNanoSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Status)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Status=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Energy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Energy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_X)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_X=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MLEnergy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_MLEnergy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MLX)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_MLX=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MLY)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_MLY=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MLZ)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_MLZ=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Px)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Px=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Py)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Py=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Pz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Pz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ScaledEnergy)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_ScaledEnergy=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ScaledX)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_ScaledX=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ScaledY)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_ScaledY=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ScaledZ)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_ScaledZ=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_NPmt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_NPmt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PERMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_PERMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PESum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_PESum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TimeRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_TimeRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_RatioMaxQ)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_RatioMaxQ=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_EarlyChargeSum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_EarlyChargeSum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MiddleChargeSum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_MiddleChargeSum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_LateChargeSum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_LateChargeSum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_EffNPmt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_EffNPmt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_EffPERMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_EffPERMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_EffPESum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_EffPESum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_EffTimeRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_EffTimeRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_EffRatioMaxQ)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_EffRatioMaxQ=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_EffRatioMaxQ123)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_EffRatioMaxQ123=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_EffRatioMaxQ3x3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_EffRatioMaxQ3x3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MiddleTimeRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_MiddleTimeRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MaxQ)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_MaxQ=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Quadrant)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Quadrant=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_PeakRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_PeakRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Kurtosis)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_Kurtosis=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_QuadrantQ1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_QuadrantQ1=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_QuadrantQ2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_QuadrantQ2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_QuadrantQ3)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_QuadrantQ3=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_QuadrantQ4)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_QuadrantQ4=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_RingKurtosis)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_RingKurtosis=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ColumnKurtosis)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_ColumnKurtosis=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MainPeakRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_MainPeakRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_SecondPeakRMS)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_SecondPeakRMS=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_charge_sum_flasher_flag)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_charge_sum_flasher_flag=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_charge_sum_flasher_max)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_charge_sum_flasher_max=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_flasher_ring)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_flasher_ring=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_flasher_column)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_flasher_column=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tRMS_local)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_tRMS_local=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tRMS_local_wo_1st_hit)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TBranch),-1,-1,1,"b_tRMS_local_wo_1st_hit=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Tree2SelectordictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTree2Selectordict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTree2Selector(void) {
   /* Tree2Selector */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Tree2SelectordictLN_Tree2Selector));
   G__memfunc_setup("Tree2Selector",1283,G__Tree2Selectordict_534_0_1, 105, G__get_linked_tagnum(&G__Tree2SelectordictLN_Tree2Selector), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Version",742,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Begin",485,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveBegin",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetOption",933,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetObject",899,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputList",1240,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputList",1357,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Tree2SelectordictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveTerminate",1444,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__Tree2Selectordict_534_0_15, 85, G__get_linked_tagnum(&G__Tree2SelectordictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Tree2Selector::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Tree2Selectordict_534_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Tree2Selector::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Tree2Selectordict_534_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Tree2Selector::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Tree2Selectordict_534_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Tree2Selector::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Tree2SelectordictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Tree2Selectordict_534_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Tree2Selectordict_534_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Tree2Selector::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Tree2Selectordict_534_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Tree2Selector::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Tree2Selectordict_534_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Tree2Selector::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Tree2Selectordict_534_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Tree2Selector::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~Tree2Selector", 1409, G__Tree2Selectordict_534_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTree2Selectordict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTree2Selectordict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTree2Selectordict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Tree2SelectordictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__Tree2SelectordictLN_Tree2Selector = { "Tree2Selector" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTree2Selectordict() {
  G__Tree2SelectordictLN_TClass.tagnum = -1 ;
  G__Tree2SelectordictLN_TBuffer.tagnum = -1 ;
  G__Tree2SelectordictLN_TMemberInspector.tagnum = -1 ;
  G__Tree2SelectordictLN_TObject.tagnum = -1 ;
  G__Tree2SelectordictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Tree2SelectordictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Tree2SelectordictLN_TList.tagnum = -1 ;
  G__Tree2SelectordictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Tree2SelectordictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Tree2SelectordictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__Tree2SelectordictLN_TTree.tagnum = -1 ;
  G__Tree2SelectordictLN_TBranch.tagnum = -1 ;
  G__Tree2SelectordictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__Tree2SelectordictLN_TSelector.tagnum = -1 ;
  G__Tree2SelectordictLN_Tree2Selector.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTree2Selectordict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_TClass);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_TObject);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_TList);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_TTree);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_TSelector);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Tree2SelectordictLN_Tree2Selector),sizeof(Tree2Selector),-1,29952,(char*)NULL,G__setup_memvarTree2Selector,G__setup_memfuncTree2Selector);
}
extern "C" void G__cpp_setupTree2Selectordict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTree2Selectordict()");
  G__set_cpp_environmentTree2Selectordict();
  G__cpp_setup_tagtableTree2Selectordict();

  G__cpp_setup_inheritanceTree2Selectordict();

  G__cpp_setup_typetableTree2Selectordict();

  G__cpp_setup_memvarTree2Selectordict();

  G__cpp_setup_memfuncTree2Selectordict();
  G__cpp_setup_globalTree2Selectordict();
  G__cpp_setup_funcTree2Selectordict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTree2Selectordict();
  return;
}
class G__cpp_setup_initTree2Selectordict {
  public:
    G__cpp_setup_initTree2Selectordict() { G__add_setup_func("Tree2Selectordict",(G__incsetup)(&G__cpp_setupTree2Selectordict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTree2Selectordict() { G__remove_setup_func("Tree2Selectordict"); }
};
G__cpp_setup_initTree2Selectordict G__cpp_setup_initializerTree2Selectordict;

