../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r00.root  MC_acrylic_r00.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r01.root  MC_acrylic_r01.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r02.root  MC_acrylic_r02.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r03.root  MC_acrylic_r03.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r04.root  MC_acrylic_r04.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r05.root  MC_acrylic_r05.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r06.root  MC_acrylic_r06.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r07.root  MC_acrylic_r07.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r08.root  MC_acrylic_r08.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r09.root  MC_acrylic_r09.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r10.root  MC_acrylic_r10.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r11.root  MC_acrylic_r11.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r12.root  MC_acrylic_r12.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r13.root  MC_acrylic_r13.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r14.root  MC_acrylic_r14.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r15.root  MC_acrylic_r15.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r16.root  MC_acrylic_r16.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r17.root  MC_acrylic_r17.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r18.root  MC_acrylic_r18.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r19.root  MC_acrylic_r19.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r20.root  MC_acrylic_r20.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r21.root  MC_acrylic_r21.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r22.root  MC_acrylic_r22.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r23.root  MC_acrylic_r23.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r24.root  MC_acrylic_r24.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r25.root  MC_acrylic_r25.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r27.root  MC_acrylic_r27.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r28.root  MC_acrylic_r28.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r29.root  MC_acrylic_r29.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r30.root  MC_acrylic_r30.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r31.root  MC_acrylic_r31.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r32.root  MC_acrylic_r32.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r33.root  MC_acrylic_r33.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r34.root  MC_acrylic_r34.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r35.root  MC_acrylic_r35.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r36.root  MC_acrylic_r36.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r37.root  MC_acrylic_r37.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r38.root  MC_acrylic_r38.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r39.root  MC_acrylic_r39.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r40.root  MC_acrylic_r40.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r41.root  MC_acrylic_r41.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r42.root  MC_acrylic_r42.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r43.root  MC_acrylic_r43.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r44.root  MC_acrylic_r44.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r45.root  MC_acrylic_r45.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r46.root  MC_acrylic_r46.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r47.root  MC_acrylic_r47.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r48.root  MC_acrylic_r48.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r49.root  MC_acrylic_r49.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r50.root  MC_acrylic_r50.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r51.root  MC_acrylic_r51.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r52.root  MC_acrylic_r52.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r53.root  MC_acrylic_r53.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r54.root  MC_acrylic_r54.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r55.root  MC_acrylic_r55.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r56.root  MC_acrylic_r56.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r57.root  MC_acrylic_r57.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r58.root  MC_acrylic_r58.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r59.root  MC_acrylic_r59.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r60.root  MC_acrylic_r60.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r61.root  MC_acrylic_r61.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r62.root  MC_acrylic_r62.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r63.root  MC_acrylic_r63.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r64.root  MC_acrylic_r64.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r65.root  MC_acrylic_r65.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r66.root  MC_acrylic_r66.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r67.root  MC_acrylic_r67.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r68.root  MC_acrylic_r68.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r69.root  MC_acrylic_r69.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r70.root  MC_acrylic_r70.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r71.root  MC_acrylic_r71.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r72.root  MC_acrylic_r72.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r73.root  MC_acrylic_r73.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r74.root  MC_acrylic_r74.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r75.root  MC_acrylic_r75.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r76.root  MC_acrylic_r76.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r77.root  MC_acrylic_r77.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r78.root  MC_acrylic_r78.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r79.root  MC_acrylic_r79.TWin.root  RunInfo.txt H
../src/Ostw  /back1/dayabay_back1/MC/Stream/IBD-acrylic/MC_acrylic_r80.root  MC_acrylic_r80.TWin.root  RunInfo.txt H
