../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r10.root  MC_GdLS_r10.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r11.root  MC_GdLS_r11.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r12.root  MC_GdLS_r12.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r13.root  MC_GdLS_r13.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r14.root  MC_GdLS_r14.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r15.root  MC_GdLS_r15.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r16.root  MC_GdLS_r16.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r17.root  MC_GdLS_r17.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r18.root  MC_GdLS_r18.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r19.root  MC_GdLS_r19.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r20.root  MC_GdLS_r20.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r21.root  MC_GdLS_r21.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r22.root  MC_GdLS_r22.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r23.root  MC_GdLS_r23.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r24.root  MC_GdLS_r24.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r25.root  MC_GdLS_r25.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r26.root  MC_GdLS_r26.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r27.root  MC_GdLS_r27.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r28.root  MC_GdLS_r28.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r29.root  MC_GdLS_r29.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r30.root  MC_GdLS_r30.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r31.root  MC_GdLS_r31.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r32.root  MC_GdLS_r32.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r33.root  MC_GdLS_r33.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r34.root  MC_GdLS_r34.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r35.root  MC_GdLS_r35.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r36.root  MC_GdLS_r36.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r37.root  MC_GdLS_r37.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r38.root  MC_GdLS_r38.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r39.root  MC_GdLS_r39.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r40.root  MC_GdLS_r40.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r41.root  MC_GdLS_r41.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r42.root  MC_GdLS_r42.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r43.root  MC_GdLS_r43.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r44.root  MC_GdLS_r44.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r45.root  MC_GdLS_r45.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r46.root  MC_GdLS_r46.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r47.root  MC_GdLS_r47.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r48.root  MC_GdLS_r48.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r49.root  MC_GdLS_r49.TWin.root RunInfo.txt H
../src/Ostw  /home/dayabay/BACK1/MC/Stream/IBD-GdLS/MC_GdLS_r50.root  MC_GdLS_r50.TWin.root RunInfo.txt H
