//
// File generated by rootcint at Mon Mar 12 15:07:42 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME StreamReaderDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "StreamReaderDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void StreamReader_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_StreamReader(void *p = 0);
   static void *newArray_StreamReader(Long_t size, void *p);
   static void delete_StreamReader(void *p);
   static void deleteArray_StreamReader(void *p);
   static void destruct_StreamReader(void *p);
   static void streamer_StreamReader(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::StreamReader*)
   {
      ::StreamReader *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::StreamReader >(0);
      static ::ROOT::TGenericClassInfo 
         instance("StreamReader", ::StreamReader::Class_Version(), "./StreamReader.h", 15,
                  typeid(::StreamReader), DefineBehavior(ptr, ptr),
                  &::StreamReader::Dictionary, isa_proxy, 0,
                  sizeof(::StreamReader) );
      instance.SetNew(&new_StreamReader);
      instance.SetNewArray(&newArray_StreamReader);
      instance.SetDelete(&delete_StreamReader);
      instance.SetDeleteArray(&deleteArray_StreamReader);
      instance.SetDestructor(&destruct_StreamReader);
      instance.SetStreamerFunc(&streamer_StreamReader);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::StreamReader*)
   {
      return GenerateInitInstanceLocal((::StreamReader*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::StreamReader*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *StreamReader::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *StreamReader::Class_Name()
{
   return "StreamReader";
}

//______________________________________________________________________________
const char *StreamReader::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::StreamReader*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int StreamReader::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::StreamReader*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void StreamReader::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::StreamReader*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *StreamReader::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::StreamReader*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void StreamReader::Streamer(TBuffer &R__b)
{
   // Stream an object of class StreamReader.

   TSelector::Streamer(R__b);
}

//______________________________________________________________________________
void StreamReader::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class StreamReader.
      TClass *R__cl = ::StreamReader::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Run", &Run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Site", &Site);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Det", &Det);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigNum", &TrigNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigType", &TrigType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigSec", &TrigSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrigNano", &TrigNano);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NPmt", &NPmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E", &E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "X", &X);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Y", &Y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Z", &Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TRms", &TRms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Quadrant", &Quadrant);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "QMax2Sum", &QMax2Sum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MaxQ2Inch", &MaxQ2Inch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Run", &b_Run);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Site", &b_Site);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Det", &b_Det);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigNum", &b_TrigNum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigType", &b_TrigType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigSec", &b_TrigSec);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TrigNano", &b_TrigNano);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_NPmt", &b_NPmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_E", &b_E);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_X", &b_X);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Y", &b_Y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Z", &b_Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_TRms", &b_TRms);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_Quadrant", &b_Quadrant);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_QMax2Sum", &b_QMax2Sum);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_MaxQ2Inch", &b_MaxQ2Inch);
      TSelector::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_StreamReader(void *p) {
      return  p ? new(p) ::StreamReader : new ::StreamReader;
   }
   static void *newArray_StreamReader(Long_t nElements, void *p) {
      return p ? new(p) ::StreamReader[nElements] : new ::StreamReader[nElements];
   }
   // Wrapper around operator delete
   static void delete_StreamReader(void *p) {
      delete ((::StreamReader*)p);
   }
   static void deleteArray_StreamReader(void *p) {
      delete [] ((::StreamReader*)p);
   }
   static void destruct_StreamReader(void *p) {
      typedef ::StreamReader current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_StreamReader(TBuffer &buf, void *obj) {
      ((::StreamReader*)obj)->::StreamReader::Streamer(buf);
   }
} // end of namespace ROOT for class ::StreamReader

/********************************************************
* StreamReaderDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableStreamReaderDict();

extern "C" void G__set_cpp_environmentStreamReaderDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("StreamReader.h");
  G__cpp_reset_tagtableStreamReaderDict();
}
#include <new>
extern "C" int G__cpp_dllrevStreamReaderDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* StreamReader */
static int G__StreamReaderDict_534_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   StreamReader* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new StreamReader((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) StreamReader((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new StreamReader[n];
       } else {
         p = new((void*) gvp) StreamReader[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new StreamReader;
       } else {
         p = new((void*) gvp) StreamReader;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__StreamReaderDictLN_StreamReader));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StreamReaderDict_534_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) StreamReader::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StreamReaderDict_534_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StreamReader::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StreamReaderDict_534_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) StreamReader::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StreamReaderDict_534_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      StreamReader::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StreamReaderDict_534_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StreamReader*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StreamReaderDict_534_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StreamReader::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StreamReaderDict_534_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) StreamReader::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StreamReaderDict_534_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StreamReader::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StreamReaderDict_534_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) StreamReader::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef StreamReader G__TStreamReader;
static int G__StreamReaderDict_534_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (StreamReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((StreamReader*) (soff+(sizeof(StreamReader)*i)))->~G__TStreamReader();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (StreamReader*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((StreamReader*) (soff))->~G__TStreamReader();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* StreamReader */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncStreamReaderDict {
 public:
  G__Sizep2memfuncStreamReaderDict(): p(&G__Sizep2memfuncStreamReaderDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncStreamReaderDict::*p)();
};

size_t G__get_sizep2memfuncStreamReaderDict()
{
  G__Sizep2memfuncStreamReaderDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceStreamReaderDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__StreamReaderDictLN_StreamReader))) {
     StreamReader *G__Lderived;
     G__Lderived=(StreamReader*)0x1000;
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__StreamReaderDictLN_StreamReader),G__get_linked_tagnum(&G__StreamReaderDictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__StreamReaderDictLN_StreamReader),G__get_linked_tagnum(&G__StreamReaderDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableStreamReaderDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StreamReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StreamReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StreamReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StreamReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__StreamReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__StreamReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* StreamReader */
static void G__setup_memvarStreamReader(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__StreamReaderDictLN_StreamReader));
   { StreamReader *p; p=(StreamReader*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->Run)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Run=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Site)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Site=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Det)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Det=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrigNum)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigNum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrigType)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigType=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrigSec)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigSec=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrigNano)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"TrigNano=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NPmt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"NPmt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->E)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"E=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->X)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"X=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Y)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Z)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TRms)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"TRms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Quadrant)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"Quadrant=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->QMax2Sum)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"QMax2Sum=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MaxQ2Inch)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"MaxQ2Inch=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_Run)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_Run=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Site)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_Site=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Det)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_Det=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigNum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_TrigNum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigType)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_TrigType=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigSec)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_TrigSec=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TrigNano)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_TrigNano=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_NPmt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_NPmt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_E)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_E=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_X)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_X=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_Y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_Z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_TRms)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_TRms=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_Quadrant)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_Quadrant=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_QMax2Sum)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_QMax2Sum=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_MaxQ2Inch)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TBranch),-1,-1,1,"b_MaxQ2Inch=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StreamReaderDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarStreamReaderDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncStreamReader(void) {
   /* StreamReader */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__StreamReaderDictLN_StreamReader));
   G__memfunc_setup("StreamReader",1215,G__StreamReaderDict_534_0_1, 105, G__get_linked_tagnum(&G__StreamReaderDictLN_StreamReader), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Version",742,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Begin",485,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveBegin",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetOption",933,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetObject",899,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputList",1240,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputList",1357,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__StreamReaderDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveTerminate",1444,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__StreamReaderDict_534_0_15, 85, G__get_linked_tagnum(&G__StreamReaderDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&StreamReader::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__StreamReaderDict_534_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&StreamReader::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__StreamReaderDict_534_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&StreamReader::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__StreamReaderDict_534_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&StreamReader::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__StreamReaderDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__StreamReaderDict_534_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__StreamReaderDict_534_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&StreamReader::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__StreamReaderDict_534_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&StreamReader::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__StreamReaderDict_534_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&StreamReader::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__StreamReaderDict_534_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&StreamReader::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~StreamReader", 1341, G__StreamReaderDict_534_0_27, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncStreamReaderDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalStreamReaderDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcStreamReaderDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__StreamReaderDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__StreamReaderDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__StreamReaderDictLN_StreamReader = { "StreamReader" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableStreamReaderDict() {
  G__StreamReaderDictLN_TClass.tagnum = -1 ;
  G__StreamReaderDictLN_TBuffer.tagnum = -1 ;
  G__StreamReaderDictLN_TMemberInspector.tagnum = -1 ;
  G__StreamReaderDictLN_TObject.tagnum = -1 ;
  G__StreamReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__StreamReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StreamReaderDictLN_TList.tagnum = -1 ;
  G__StreamReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__StreamReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StreamReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__StreamReaderDictLN_TTree.tagnum = -1 ;
  G__StreamReaderDictLN_TBranch.tagnum = -1 ;
  G__StreamReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__StreamReaderDictLN_TSelector.tagnum = -1 ;
  G__StreamReaderDictLN_StreamReader.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableStreamReaderDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_TList);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_TSelector);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__StreamReaderDictLN_StreamReader),sizeof(StreamReader),-1,29952,(char*)NULL,G__setup_memvarStreamReader,G__setup_memfuncStreamReader);
}
extern "C" void G__cpp_setupStreamReaderDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupStreamReaderDict()");
  G__set_cpp_environmentStreamReaderDict();
  G__cpp_setup_tagtableStreamReaderDict();

  G__cpp_setup_inheritanceStreamReaderDict();

  G__cpp_setup_typetableStreamReaderDict();

  G__cpp_setup_memvarStreamReaderDict();

  G__cpp_setup_memfuncStreamReaderDict();
  G__cpp_setup_globalStreamReaderDict();
  G__cpp_setup_funcStreamReaderDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncStreamReaderDict();
  return;
}
class G__cpp_setup_initStreamReaderDict {
  public:
    G__cpp_setup_initStreamReaderDict() { G__add_setup_func("StreamReaderDict",(G__incsetup)(&G__cpp_setupStreamReaderDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initStreamReaderDict() { G__remove_setup_func("StreamReaderDict"); }
};
G__cpp_setup_initStreamReaderDict G__cpp_setup_initializerStreamReaderDict;

