/********************************************************************
* RunStatDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RunStatDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableRunStatDict();
extern void G__cpp_setup_inheritanceRunStatDict();
extern void G__cpp_setup_typetableRunStatDict();
extern void G__cpp_setup_memvarRunStatDict();
extern void G__cpp_setup_globalRunStatDict();
extern void G__cpp_setup_memfuncRunStatDict();
extern void G__cpp_setup_funcRunStatDict();
extern void G__set_cpp_environmentRunStatDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "RunStat.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RunStatDictLN_TClass;
extern G__linked_taginfo G__RunStatDictLN_TBuffer;
extern G__linked_taginfo G__RunStatDictLN_TMemberInspector;
extern G__linked_taginfo G__RunStatDictLN_TObject;
extern G__linked_taginfo G__RunStatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RunStatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RunStatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__RunStatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RunStatDictLN_RunStat;

/* STUB derived class for protected member access */
